/**
 * ♿ Accessibility Checker
 * 
 * Check WCAG compliance:
 * - Color contrast
 * - ARIA roles
 * - Keyboard navigation
 */

import { EventEmitter } from 'events';

export class AccessibilityChecker extends EventEmitter {
    private static instance: AccessibilityChecker;

    private constructor() { super(); }

    static getInstance(): AccessibilityChecker {
        if (!AccessibilityChecker.instance) {
            AccessibilityChecker.instance = new AccessibilityChecker();
        }
        return AccessibilityChecker.instance;
    }

    generateAccessibilityUtils(): string {
        return `// Accessibility Utilities
// Generated by Shadow AI

// Color Contrast Checker
export function getContrastRatio(color1: string, color2: string): number {
    const lum1 = getLuminance(hexToRgb(color1));
    const lum2 = getLuminance(hexToRgb(color2));
    
    const brightest = Math.max(lum1, lum2);
    const darkest = Math.min(lum1, lum2);
    
    return (brightest + 0.05) / (darkest + 0.05);
}

export function meetsWCAG(ratio: number, level: 'AA' | 'AAA', size: 'normal' | 'large'): boolean {
    if (level === 'AAA') {
        return size === 'large' ? ratio >= 4.5 : ratio >= 7;
    }
    return size === 'large' ? ratio >= 3 : ratio >= 4.5;
}

function getLuminance(rgb: [number, number, number]): number {
    const [r, g, b] = rgb.map(c => {
        c /= 255;
        return c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
    });
    return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

function hexToRgb(hex: string): [number, number, number] {
    const result = /^#?([a-f\\d]{2})([a-f\\d]{2})([a-f\\d]{2})$/i.exec(hex);
    return result ? [
        parseInt(result[1], 16),
        parseInt(result[2], 16),
        parseInt(result[3], 16)
    ] : [0, 0, 0];
}

// Focus Trap Hook
export function useFocusTrap(containerRef: React.RefObject<HTMLElement>, active: boolean) {
    useEffect(() => {
        if (!active || !containerRef.current) return;
        
        const container = containerRef.current;
        const focusableElements = container.querySelectorAll(
            'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
        );
        
        const firstEl = focusableElements[0] as HTMLElement;
        const lastEl = focusableElements[focusableElements.length - 1] as HTMLElement;
        
        function handleKeyDown(e: KeyboardEvent) {
            if (e.key !== 'Tab') return;
            
            if (e.shiftKey && document.activeElement === firstEl) {
                e.preventDefault();
                lastEl.focus();
            } else if (!e.shiftKey && document.activeElement === lastEl) {
                e.preventDefault();
                firstEl.focus();
            }
        }
        
        container.addEventListener('keydown', handleKeyDown);
        firstEl?.focus();
        
        return () => container.removeEventListener('keydown', handleKeyDown);
    }, [active, containerRef]);
}

// Announce to Screen Readers
export function announce(message: string, priority: 'polite' | 'assertive' = 'polite') {
    const announcer = document.createElement('div');
    announcer.setAttribute('aria-live', priority);
    announcer.setAttribute('aria-atomic', 'true');
    announcer.setAttribute('class', 'sr-only');
    document.body.appendChild(announcer);
    
    setTimeout(() => {
        announcer.textContent = message;
        setTimeout(() => announcer.remove(), 1000);
    }, 100);
}

// Skip Link Component
export function SkipLink({ href = '#main-content', children = 'Skip to content' }) {
    return (
        <a
            href={href}
            className="skip-link"
            style={{
                position: 'absolute',
                top: '-100%',
                left: 0,
                padding: '8px 16px',
                background: 'var(--color-primary)',
                color: 'white',
                zIndex: 9999,
            }}
            onFocus={(e) => e.target.style.top = '0'}
            onBlur={(e) => e.target.style.top = '-100%'}
        >
            {children}
        </a>
    );
}

// Accessible Modal
export function Modal({ isOpen, onClose, title, children }) {
    const modalRef = useRef<HTMLDivElement>(null);
    
    useFocusTrap(modalRef, isOpen);
    
    useEffect(() => {
        const handleEscape = (e: KeyboardEvent) => {
            if (e.key === 'Escape' && isOpen) onClose();
        };
        document.addEventListener('keydown', handleEscape);
        return () => document.removeEventListener('keydown', handleEscape);
    }, [isOpen, onClose]);
    
    if (!isOpen) return null;
    
    return createPortal(
        <div
            role="dialog"
            aria-modal="true"
            aria-labelledby="modal-title"
            ref={modalRef}
        >
            <div className="modal-overlay" onClick={onClose} />
            <div className="modal-content">
                <h2 id="modal-title">{title}</h2>
                {children}
                <button onClick={onClose} aria-label="Close modal">×</button>
            </div>
        </div>,
        document.body
    );
}

// Screen Reader Only CSS
export const srOnlyStyles = \`
.sr-only {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    white-space: nowrap;
    border: 0;
}
\`;

// ARIA Helpers
export const ariaProps = {
    button: (expanded?: boolean) => ({
        role: 'button',
        tabIndex: 0,
        'aria-expanded': expanded,
        onKeyDown: (e: KeyboardEvent) => {
            if (e.key === 'Enter' || e.key === ' ') {
                e.preventDefault();
                (e.target as HTMLElement).click();
            }
        }
    }),
    
    menu: (isOpen: boolean) => ({
        role: 'menu',
        'aria-hidden': !isOpen,
        tabIndex: -1
    }),
    
    menuItem: () => ({
        role: 'menuitem',
        tabIndex: -1
    }),
    
    tab: (selected: boolean, controls: string) => ({
        role: 'tab',
        'aria-selected': selected,
        'aria-controls': controls,
        tabIndex: selected ? 0 : -1
    }),
    
    tabPanel: (id: string, labelledBy: string, hidden: boolean) => ({
        role: 'tabpanel',
        id,
        'aria-labelledby': labelledBy,
        hidden,
        tabIndex: 0
    })
};
`;
    }

    generateChecklist(): string[] {
        return [
            'All images have alt text',
            'Form inputs have labels',
            'Color contrast meets WCAG AA (4.5:1)',
            'Focus indicators are visible',
            'Page can be navigated by keyboard',
            'Skip links are present',
            'Headings are hierarchical (h1 > h2 > h3)',
            'ARIA roles are used correctly',
            'Error messages are announced',
            'Modal dialogs trap focus',
            'Links are descriptive (not "click here")',
            'Touch targets are at least 44x44px',
            'Animations respect prefers-reduced-motion',
            'Lang attribute is set on <html>'
        ];
    }
}

export const accessibilityChecker = AccessibilityChecker.getInstance();
