/**
 * 🔷 Angular Generator
 * 
 * Generate Angular code:
 * - Components, services, RxJS
 */

import { EventEmitter } from 'events';

export class AngularGenerator extends EventEmitter {
    private static instance: AngularGenerator;

    private constructor() { super(); }

    static getInstance(): AngularGenerator {
        if (!AngularGenerator.instance) {
            AngularGenerator.instance = new AngularGenerator();
        }
        return AngularGenerator.instance;
    }

    generateApp(): string {
        return `// Angular App Structure
// Generated by Shadow AI

// app.config.ts
import { ApplicationConfig, provideZoneChangeDetection } from '@angular/core';
import { provideRouter, withComponentInputBinding } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { provideAnimations } from '@angular/platform-browser/animations';
import { routes } from './app.routes';
import { authInterceptor } from './interceptors/auth.interceptor';

export const appConfig: ApplicationConfig = {
    providers: [
        provideZoneChangeDetection({ eventCoalescing: true }),
        provideRouter(routes, withComponentInputBinding()),
        provideHttpClient(withInterceptors([authInterceptor])),
        provideAnimations()
    ]
};

// app.routes.ts
import { Routes } from '@angular/router';
import { authGuard } from './guards/auth.guard';

export const routes: Routes = [
    { path: '', loadComponent: () => import('./pages/home/home.component').then(m => m.HomeComponent) },
    { path: 'login', loadComponent: () => import('./pages/login/login.component').then(m => m.LoginComponent) },
    { 
        path: 'dashboard', 
        loadComponent: () => import('./pages/dashboard/dashboard.component').then(m => m.DashboardComponent),
        canActivate: [authGuard]
    },
    { path: '**', redirectTo: '' }
];

// app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { HeaderComponent } from './components/header/header.component';
import { FooterComponent } from './components/footer/footer.component';

@Component({
    selector: 'app-root',
    standalone: true,
    imports: [RouterOutlet, HeaderComponent, FooterComponent],
    template: \`
        <app-header />
        <main [@routeAnimation]="outlet.activatedRouteData['animation']">
            <router-outlet #outlet="outlet" />
        </main>
        <app-footer />
    \`,
    animations: [routeAnimation]
})
export class AppComponent {}
`;
    }

    generateComponent(name: string): string {
        const lower = name.toLowerCase();
        return `// ${name} Component
// Generated by Shadow AI

import { Component, Input, Output, EventEmitter, OnInit, OnDestroy, inject, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Subject, takeUntil } from 'rxjs';
import { ${name}Service } from './${lower}.service';

@Component({
    selector: 'app-${lower}',
    standalone: true,
    imports: [CommonModule, ReactiveFormsModule],
    template: \`
        <div class="${lower}">
            <h2>{{ title() }}</h2>
            
            @if (loading()) {
                <div class="loading">Loading...</div>
            } @else if (error()) {
                <div class="error">{{ error() }}</div>
            } @else {
                <ul>
                    @for (item of items(); track item.id) {
                        <li [class.selected]="selectedId() === item.id" (click)="select(item)">
                            {{ item.name }}
                        </li>
                    } @empty {
                        <li class="empty">No items found</li>
                    }
                </ul>
            }

            <form [formGroup]="form" (ngSubmit)="onSubmit()">
                <input formControlName="name" placeholder="Name" />
                @if (form.get('name')?.invalid && form.get('name')?.touched) {
                    <span class="error">Name is required</span>
                }
                <button type="submit" [disabled]="form.invalid">Add</button>
            </form>
        </div>
    \`,
    styles: [\`
        .${lower} { padding: 1rem; }
        ul { list-style: none; padding: 0; }
        li { padding: 0.5rem; cursor: pointer; }
        li:hover { background: #f0f0f0; }
        li.selected { background: #e0e0ff; }
        .error { color: red; font-size: 0.8rem; }
    \`]
})
export class ${name}Component implements OnInit, OnDestroy {
    private destroy$ = new Subject<void>();
    private ${lower}Service = inject(${name}Service);
    private fb = inject(FormBuilder);

    @Input() initialTitle = '${name}';
    @Output() itemSelected = new EventEmitter<any>();

    // Signals
    title = signal(this.initialTitle);
    items = signal<any[]>([]);
    loading = signal(false);
    error = signal<string | null>(null);
    selectedId = signal<string | null>(null);

    // Computed
    itemCount = computed(() => this.items().length);

    // Form
    form: FormGroup = this.fb.group({
        name: ['', Validators.required]
    });

    ngOnInit() {
        this.loadItems();
    }

    ngOnDestroy() {
        this.destroy$.next();
        this.destroy$.complete();
    }

    loadItems() {
        this.loading.set(true);
        this.${lower}Service.getAll()
            .pipe(takeUntil(this.destroy$))
            .subscribe({
                next: (data) => {
                    this.items.set(data);
                    this.loading.set(false);
                },
                error: (err) => {
                    this.error.set(err.message);
                    this.loading.set(false);
                }
            });
    }

    select(item: any) {
        this.selectedId.set(item.id);
        this.itemSelected.emit(item);
    }

    onSubmit() {
        if (this.form.valid) {
            this.${lower}Service.create(this.form.value)
                .pipe(takeUntil(this.destroy$))
                .subscribe({
                    next: (newItem) => {
                        this.items.update(items => [...items, newItem]);
                        this.form.reset();
                    }
                });
        }
    }
}
`;
    }

    generateService(name: string): string {
        const lower = name.toLowerCase();
        return `// ${name}Service
// Generated by Shadow AI

import { Injectable, inject } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable, BehaviorSubject, catchError, tap, map, shareReplay } from 'rxjs';

export interface ${name} {
    id: string;
    name: string;
    [key: string]: any;
}

@Injectable({ providedIn: 'root' })
export class ${name}Service {
    private http = inject(HttpClient);
    private baseUrl = '/api/${lower}s';

    // Cache
    private cache$ = new BehaviorSubject<${name}[]>([]);
    private loaded = false;

    getAll(params?: Record<string, string>): Observable<${name}[]> {
        if (this.loaded) {
            return this.cache$.asObservable();
        }

        let httpParams = new HttpParams();
        if (params) {
            Object.entries(params).forEach(([key, value]) => {
                httpParams = httpParams.set(key, value);
            });
        }

        return this.http.get<${name}[]>(this.baseUrl, { params: httpParams }).pipe(
            tap(data => {
                this.cache$.next(data);
                this.loaded = true;
            }),
            shareReplay(1)
        );
    }

    getById(id: string): Observable<${name}> {
        return this.http.get<${name}>(\`\${this.baseUrl}/\${id}\`);
    }

    create(data: Partial<${name}>): Observable<${name}> {
        return this.http.post<${name}>(this.baseUrl, data).pipe(
            tap(newItem => {
                const current = this.cache$.value;
                this.cache$.next([...current, newItem]);
            })
        );
    }

    update(id: string, data: Partial<${name}>): Observable<${name}> {
        return this.http.patch<${name}>(\`\${this.baseUrl}/\${id}\`, data).pipe(
            tap(updated => {
                const current = this.cache$.value;
                this.cache$.next(current.map(item => item.id === id ? updated : item));
            })
        );
    }

    delete(id: string): Observable<void> {
        return this.http.delete<void>(\`\${this.baseUrl}/\${id}\`).pipe(
            tap(() => {
                const current = this.cache$.value;
                this.cache$.next(current.filter(item => item.id !== id));
            })
        );
    }

    clearCache() {
        this.cache$.next([]);
        this.loaded = false;
    }
}
`;
    }

    generateGuard(): string {
        return `// Auth Guard
// Generated by Shadow AI

import { inject } from '@angular/core';
import { Router, CanActivateFn } from '@angular/router';
import { AuthService } from '../services/auth.service';

export const authGuard: CanActivateFn = (route, state) => {
    const authService = inject(AuthService);
    const router = inject(Router);

    if (authService.isAuthenticated()) {
        return true;
    }

    router.navigate(['/login'], { queryParams: { returnUrl: state.url } });
    return false;
};
`;
    }
}

export const angularGenerator = AngularGenerator.getInstance();
