/**
 * 🤖 Bot Generator
 * 
 * Generate chat bots:
 * - Discord, Slack, Telegram
 */

import { EventEmitter } from 'events';

export type BotPlatform = 'discord' | 'slack' | 'telegram';

export class BotGenerator extends EventEmitter {
    private static instance: BotGenerator;

    private constructor() { super(); }

    static getInstance(): BotGenerator {
        if (!BotGenerator.instance) {
            BotGenerator.instance = new BotGenerator();
        }
        return BotGenerator.instance;
    }

    getPlatforms(): BotPlatform[] {
        return ['discord', 'slack', 'telegram'];
    }

    generate(platform: BotPlatform): string {
        switch (platform) {
            case 'discord': return this.generateDiscord();
            case 'slack': return this.generateSlack();
            case 'telegram': return this.generateTelegram();
            default: return '';
        }
    }

    private generateDiscord(): string {
        return `// Discord Bot
// Generated by Shadow AI

import { Client, GatewayIntentBits, Partials, SlashCommandBuilder, REST, Routes, EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle } from 'discord.js';

const client = new Client({
    intents: [
        GatewayIntentBits.Guilds,
        GatewayIntentBits.GuildMessages,
        GatewayIntentBits.MessageContent,
        GatewayIntentBits.GuildMembers,
        GatewayIntentBits.DirectMessages
    ],
    partials: [Partials.Message, Partials.Channel]
});

// Commands
const commands = [
    new SlashCommandBuilder().setName('ping').setDescription('Replies with Pong!'),
    new SlashCommandBuilder().setName('info').setDescription('Get user info').addUserOption(opt => opt.setName('user').setDescription('The user').setRequired(false)),
    new SlashCommandBuilder().setName('poll').setDescription('Create a poll').addStringOption(opt => opt.setName('question').setDescription('The poll question').setRequired(true))
].map(cmd => cmd.toJSON());

// Register commands
async function registerCommands() {
    const rest = new REST({ version: '10' }).setToken(process.env.DISCORD_TOKEN!);
    await rest.put(Routes.applicationCommands(process.env.DISCORD_CLIENT_ID!), { body: commands });
    console.log('Commands registered');
}

// Ready event
client.once('ready', () => {
    console.log(\`Bot is ready as \${client.user?.tag}\`);
    client.user?.setActivity('with code', { type: 0 });
    registerCommands();
});

// Slash command handler
client.on('interactionCreate', async (interaction) => {
    if (!interaction.isChatInputCommand()) return;

    switch (interaction.commandName) {
        case 'ping':
            const latency = Date.now() - interaction.createdTimestamp;
            await interaction.reply(\`🏓 Pong! Latency: \${latency}ms\`);
            break;

        case 'info':
            const user = interaction.options.getUser('user') || interaction.user;
            const embed = new EmbedBuilder()
                .setTitle(\`User Info: \${user.username}\`)
                .setThumbnail(user.displayAvatarURL())
                .addFields(
                    { name: 'ID', value: user.id, inline: true },
                    { name: 'Created', value: user.createdAt.toDateString(), inline: true }
                )
                .setColor('#667eea');
            await interaction.reply({ embeds: [embed] });
            break;

        case 'poll':
            const question = interaction.options.getString('question')!;
            const pollEmbed = new EmbedBuilder()
                .setTitle('📊 Poll')
                .setDescription(question)
                .setColor('#667eea');
            
            const row = new ActionRowBuilder<ButtonBuilder>()
                .addComponents(
                    new ButtonBuilder().setCustomId('yes').setLabel('Yes').setStyle(ButtonStyle.Success),
                    new ButtonBuilder().setCustomId('no').setLabel('No').setStyle(ButtonStyle.Danger)
                );
            
            await interaction.reply({ embeds: [pollEmbed], components: [row] });
            break;
    }
});

// Button handler
client.on('interactionCreate', async (interaction) => {
    if (!interaction.isButton()) return;
    
    if (['yes', 'no'].includes(interaction.customId)) {
        await interaction.reply({ content: \`You voted \${interaction.customId}!\`, ephemeral: true });
    }
});

// Message handler
client.on('messageCreate', async (message) => {
    if (message.author.bot) return;
    
    if (message.content.toLowerCase() === 'hello') {
        await message.reply('Hello! 👋');
    }
});

client.login(process.env.DISCORD_TOKEN);
`;
    }

    private generateSlack(): string {
        return `// Slack Bot
// Generated by Shadow AI

import { App, LogLevel } from '@slack/bolt';

const app = new App({
    token: process.env.SLACK_BOT_TOKEN,
    signingSecret: process.env.SLACK_SIGNING_SECRET,
    socketMode: true,
    appToken: process.env.SLACK_APP_TOKEN,
    logLevel: LogLevel.INFO
});

// Slash command
app.command('/hello', async ({ command, ack, respond }) => {
    await ack();
    await respond({
        text: \`Hey <@\${command.user_id}>! 👋\`,
        response_type: 'in_channel'
    });
});

// Message listener
app.message('hello', async ({ message, say }) => {
    await say(\`Hello <@\${message.user}>! How can I help you?\`);
});

// Mention handler
app.event('app_mention', async ({ event, say }) => {
    await say(\`Thanks for mentioning me <@\${event.user}>! Use /help to see commands.\`);
});

// Interactive button
app.action('button_click', async ({ body, ack, say }) => {
    await ack();
    await say(\`<@\${body.user.id}> clicked the button!\`);
});

// Modal submission
app.view('modal_submit', async ({ ack, body, view, client }) => {
    await ack();
    const values = view.state.values;
    const inputValue = values.input_block.input_action.value;
    
    await client.chat.postMessage({
        channel: body.user.id,
        text: \`You submitted: \${inputValue}\`
    });
});

// Home tab
app.event('app_home_opened', async ({ event, client }) => {
    await client.views.publish({
        user_id: event.user,
        view: {
            type: 'home',
            blocks: [
                { type: 'section', text: { type: 'mrkdwn', text: '*Welcome to My Bot!* 🎉' } },
                { type: 'divider' },
                { type: 'section', text: { type: 'mrkdwn', text: 'Use /hello to get started' } }
            ]
        }
    });
});

(async () => {
    await app.start(process.env.PORT || 3000);
    console.log('⚡️ Slack bot is running!');
})();
`;
    }

    private generateTelegram(): string {
        return `// Telegram Bot
// Generated by Shadow AI

import { Telegraf, Markup, session } from 'telegraf';

const bot = new Telegraf(process.env.TELEGRAM_TOKEN!);

// Session middleware
bot.use(session());

// Start command
bot.start(async (ctx) => {
    await ctx.reply(
        'Welcome! 👋 I am your assistant bot.',
        Markup.keyboard([
            ['📊 Stats', '⚙️ Settings'],
            ['ℹ️ Help']
        ]).resize()
    );
});

// Help command
bot.help(async (ctx) => {
    await ctx.reply(\`
*Available Commands:*
/start - Start the bot
/help - Show this help
/stats - Show statistics
/settings - Configure settings
    \`, { parse_mode: 'Markdown' });
});

// Text handlers
bot.hears('📊 Stats', async (ctx) => {
    await ctx.reply('Here are your stats: ...');
});

bot.hears('⚙️ Settings', async (ctx) => {
    await ctx.reply(
        'Settings:',
        Markup.inlineKeyboard([
            [Markup.button.callback('Notifications', 'settings_notifications')],
            [Markup.button.callback('Language', 'settings_language')]
        ])
    );
});

// Callback queries
bot.action('settings_notifications', async (ctx) => {
    await ctx.answerCbQuery();
    await ctx.editMessageText(
        'Notification settings:',
        Markup.inlineKeyboard([
            [Markup.button.callback('✅ Enabled', 'notif_on')],
            [Markup.button.callback('❌ Disabled', 'notif_off')],
            [Markup.button.callback('« Back', 'settings_back')]
        ])
    );
});

// Handle any text
bot.on('text', async (ctx) => {
    const text = ctx.message.text;
    await ctx.reply(\`You said: \${text}\`);
});

// Handle photos
bot.on('photo', async (ctx) => {
    const photo = ctx.message.photo[ctx.message.photo.length - 1];
    await ctx.reply(\`Received photo with ID: \${photo.file_id}\`);
});

// Error handling
bot.catch((err, ctx) => {
    console.error('Bot error:', err);
    ctx.reply('An error occurred. Please try again.');
});

// Launch
bot.launch();

// Graceful shutdown
process.once('SIGINT', () => bot.stop('SIGINT'));
process.once('SIGTERM', () => bot.stop('SIGTERM'));
`;
    }
}

export const botGenerator = BotGenerator.getInstance();
