/**
 * 🌐 Browser Extension Generator
 * 
 * Generate browser extensions:
 * - Chrome, Firefox (Manifest V3)
 */

import { EventEmitter } from 'events';

export class BrowserExtensionGenerator extends EventEmitter {
    private static instance: BrowserExtensionGenerator;

    private constructor() { super(); }

    static getInstance(): BrowserExtensionGenerator {
        if (!BrowserExtensionGenerator.instance) {
            BrowserExtensionGenerator.instance = new BrowserExtensionGenerator();
        }
        return BrowserExtensionGenerator.instance;
    }

    generateManifest(): string {
        return `// Manifest V3 (Chrome/Firefox)
// Generated by Shadow AI

{
    "manifest_version": 3,
    "name": "My Extension",
    "version": "1.0.0",
    "description": "A powerful browser extension",
    
    "permissions": [
        "storage",
        "activeTab",
        "scripting",
        "contextMenus",
        "notifications",
        "alarms"
    ],
    
    "host_permissions": [
        "https://*.example.com/*"
    ],
    
    "background": {
        "service_worker": "background.js",
        "type": "module"
    },
    
    "content_scripts": [{
        "matches": ["https://*.example.com/*"],
        "js": ["content.js"],
        "css": ["content.css"],
        "run_at": "document_idle"
    }],
    
    "action": {
        "default_popup": "popup.html",
        "default_icon": {
            "16": "icons/icon-16.png",
            "48": "icons/icon-48.png",
            "128": "icons/icon-128.png"
        },
        "default_title": "My Extension"
    },
    
    "options_page": "options.html",
    
    "icons": {
        "16": "icons/icon-16.png",
        "48": "icons/icon-48.png",
        "128": "icons/icon-128.png"
    },
    
    "web_accessible_resources": [{
        "resources": ["injected.js"],
        "matches": ["https://*.example.com/*"]
    }],
    
    "commands": {
        "_execute_action": {
            "suggested_key": { "default": "Ctrl+Shift+Y" },
            "description": "Open popup"
        },
        "toggle-feature": {
            "suggested_key": { "default": "Alt+T" },
            "description": "Toggle feature"
        }
    }
}`;
    }

    generateBackground(): string {
        return `// Background Service Worker
// Generated by Shadow AI

// Listen for installation
chrome.runtime.onInstalled.addListener(async (details) => {
    if (details.reason === 'install') {
        console.log('Extension installed');
        
        // Set default settings
        await chrome.storage.sync.set({
            enabled: true,
            theme: 'auto',
            notifications: true
        });
        
        // Open onboarding page
        chrome.tabs.create({ url: 'onboarding.html' });
    } else if (details.reason === 'update') {
        console.log('Extension updated to', chrome.runtime.getManifest().version);
    }
});

// Context menu
chrome.runtime.onInstalled.addListener(() => {
    chrome.contextMenus.create({
        id: 'main-action',
        title: 'Process with My Extension',
        contexts: ['selection', 'page']
    });
});

chrome.contextMenus.onClicked.addListener((info, tab) => {
    if (info.menuItemId === 'main-action') {
        if (info.selectionText) {
            processText(info.selectionText);
        }
    }
});

// Message handling
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
    console.log('Message received:', message, 'from:', sender);
    
    switch (message.type) {
        case 'GET_DATA':
            getData().then(sendResponse);
            return true; // Will respond asynchronously
        
        case 'SAVE_DATA':
            saveData(message.data).then(sendResponse);
            return true;
        
        case 'FETCH_API':
            fetchFromAPI(message.url).then(sendResponse);
            return true;
        
        default:
            sendResponse({ error: 'Unknown message type' });
    }
});

// Tab events
chrome.tabs.onUpdated.addListener((tabId, changeInfo, tab) => {
    if (changeInfo.status === 'complete' && tab.url?.includes('example.com')) {
        chrome.tabs.sendMessage(tabId, { type: 'PAGE_LOADED' });
    }
});

// Alarms for scheduled tasks
chrome.alarms.create('sync-data', { periodInMinutes: 30 });

chrome.alarms.onAlarm.addListener((alarm) => {
    if (alarm.name === 'sync-data') {
        syncData();
    }
});

// Storage
async function getData() {
    return chrome.storage.sync.get(['enabled', 'settings']);
}

async function saveData(data) {
    await chrome.storage.sync.set(data);
    return { success: true };
}

// API calls
async function fetchFromAPI(url) {
    try {
        const response = await fetch(url);
        return await response.json();
    } catch (error) {
        return { error: error.message };
    }
}

// Badge
function updateBadge(count) {
    chrome.action.setBadgeText({ text: count > 0 ? String(count) : '' });
    chrome.action.setBadgeBackgroundColor({ color: '#667eea' });
}

// Notifications
function showNotification(title, message) {
    chrome.notifications.create({
        type: 'basic',
        iconUrl: 'icons/icon-128.png',
        title,
        message
    });
}`;
    }

    generateContentScript(): string {
        return `// Content Script
// Generated by Shadow AI

(function() {
    'use strict';
    
    console.log('Content script loaded on:', window.location.href);
    
    // Inject styles
    const style = document.createElement('style');
    style.textContent = \`
        .my-extension-highlight { background: yellow !important; }
        .my-extension-overlay { 
            position: fixed; top: 0; right: 0; 
            padding: 10px; background: #667eea; color: white; 
            z-index: 999999; 
        }
    \`;
    document.head.appendChild(style);
    
    // Listen for messages from background
    chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
        switch (message.type) {
            case 'PAGE_LOADED':
                initializeFeatures();
                break;
            case 'TOGGLE_FEATURE':
                toggleFeature(message.enabled);
                break;
            case 'GET_PAGE_DATA':
                sendResponse(getPageData());
                break;
        }
    });
    
    // Initialize
    async function initializeFeatures() {
        const settings = await chrome.storage.sync.get(['enabled']);
        if (settings.enabled) {
            setupObserver();
            addOverlay();
        }
    }
    
    // DOM Observer
    function setupObserver() {
        const observer = new MutationObserver((mutations) => {
            mutations.forEach((mutation) => {
                mutation.addedNodes.forEach((node) => {
                    if (node.nodeType === 1) {
                        processElement(node);
                    }
                });
            });
        });
        
        observer.observe(document.body, {
            childList: true,
            subtree: true
        });
    }
    
    function processElement(element) {
        // Your processing logic here
    }
    
    function getPageData() {
        return {
            title: document.title,
            url: window.location.href,
            text: document.body.innerText.slice(0, 1000)
        };
    }
    
    function addOverlay() {
        const overlay = document.createElement('div');
        overlay.className = 'my-extension-overlay';
        overlay.textContent = 'Extension Active';
        document.body.appendChild(overlay);
    }
    
    // Send message to background
    function sendToBackground(type, data) {
        return chrome.runtime.sendMessage({ type, ...data });
    }
    
    // Initialize on load
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', initializeFeatures);
    } else {
        initializeFeatures();
    }
})();`;
    }

    generatePopup(): string {
        return `// Popup HTML + React
// Generated by Shadow AI

// popup.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="popup.css">
</head>
<body>
    <div id="root"></div>
    <script type="module" src="popup.js"></script>
</body>
</html>

// popup.tsx (React)
import React, { useState, useEffect } from 'react';
import { createRoot } from 'react-dom/client';

function Popup() {
    const [enabled, setEnabled] = useState(false);
    const [data, setData] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        loadSettings();
    }, []);

    async function loadSettings() {
        const settings = await chrome.storage.sync.get(['enabled']);
        setEnabled(settings.enabled ?? false);
        setLoading(false);
    }

    async function toggleEnabled() {
        const newValue = !enabled;
        await chrome.storage.sync.set({ enabled: newValue });
        setEnabled(newValue);
        
        // Notify content script
        const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
        if (tab?.id) {
            chrome.tabs.sendMessage(tab.id, { type: 'TOGGLE_FEATURE', enabled: newValue });
        }
    }

    async function fetchPageData() {
        const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
        if (tab?.id) {
            const response = await chrome.tabs.sendMessage(tab.id, { type: 'GET_PAGE_DATA' });
            setData(response);
        }
    }

    if (loading) return <div className="loading">Loading...</div>;

    return (
        <div className="popup">
            <header>
                <h1>My Extension</h1>
                <label className="switch">
                    <input type="checkbox" checked={enabled} onChange={toggleEnabled} />
                    <span className="slider"></span>
                </label>
            </header>
            
            <main>
                <button onClick={fetchPageData}>Analyze Page</button>
                {data && (
                    <div className="data">
                        <h3>{data.title}</h3>
                        <p>{data.url}</p>
                    </div>
                )}
            </main>
            
            <footer>
                <a href="options.html" target="_blank">Settings</a>
            </footer>
        </div>
    );
}

createRoot(document.getElementById('root')!).render(<Popup />);`;
    }
}

export const browserExtensionGenerator = BrowserExtensionGenerator.getInstance();
