/**
 * 📦 ComponentLibrary
 * 
 * UI component library:
 * - Buttons, inputs, modals, cards
 */

import { EventEmitter } from 'events';

export class ComponentLibrary extends EventEmitter {
    private static instance: ComponentLibrary;
    private constructor() { super(); }
    static getInstance(): ComponentLibrary {
        if (!ComponentLibrary.instance) {
            ComponentLibrary.instance = new ComponentLibrary();
        }
        return ComponentLibrary.instance;
    }

    generate(): string {
        return `// Component Library - Buttons, inputs, modals, cards
// Generated by Shadow AI

// Button Component
interface ButtonProps {
    variant?: 'primary' | 'secondary' | 'outline' | 'ghost' | 'danger';
    size?: 'sm' | 'md' | 'lg';
    loading?: boolean;
    disabled?: boolean;
    children: React.ReactNode;
    onClick?: () => void;
}

export function Button({ variant = 'primary', size = 'md', loading, disabled, children, onClick }: ButtonProps) {
    return (
        <button
            className={\`btn btn-\${variant} btn-\${size} \${loading ? 'loading' : ''}\`}
            disabled={disabled || loading}
            onClick={onClick}
        >
            {loading && <Spinner size="sm" />}
            {children}
        </button>
    );
}

// Input Component
interface InputProps {
    type?: string;
    label?: string;
    error?: string;
    helper?: string;
    leftIcon?: React.ReactNode;
    rightIcon?: React.ReactNode;
}

export function Input({ type = 'text', label, error, helper, leftIcon, rightIcon, ...props }: InputProps) {
    return (
        <div className={\`input-group \${error ? 'error' : ''}\`}>
            {label && <label>{label}</label>}
            <div className="input-wrapper">
                {leftIcon && <span className="icon left">{leftIcon}</span>}
                <input type={type} {...props} />
                {rightIcon && <span className="icon right">{rightIcon}</span>}
            </div>
            {error && <span className="error-text">{error}</span>}
            {helper && !error && <span className="helper-text">{helper}</span>}
        </div>
    );
}

// Modal Component
interface ModalProps {
    open: boolean;
    onClose: () => void;
    title?: string;
    children: React.ReactNode;
    size?: 'sm' | 'md' | 'lg' | 'full';
}

export function Modal({ open, onClose, title, children, size = 'md' }: ModalProps) {
    if (!open) return null;
    
    return (
        <div className="modal-overlay" onClick={onClose}>
            <div className={\`modal modal-\${size}\`} onClick={(e) => e.stopPropagation()}>
                <div className="modal-header">
                    {title && <h2>{title}</h2>}
                    <button className="close-btn" onClick={onClose}>×</button>
                </div>
                <div className="modal-body">{children}</div>
            </div>
        </div>
    );
}

// Card Component
interface CardProps {
    title?: string;
    description?: string;
    image?: string;
    footer?: React.ReactNode;
    children?: React.ReactNode;
    onClick?: () => void;
}

export function Card({ title, description, image, footer, children, onClick }: CardProps) {
    return (
        <div className={\`card \${onClick ? 'clickable' : ''}\`} onClick={onClick}>
            {image && <img src={image} alt={title} className="card-image" />}
            <div className="card-body">
                {title && <h3 className="card-title">{title}</h3>}
                {description && <p className="card-description">{description}</p>}
                {children}
            </div>
            {footer && <div className="card-footer">{footer}</div>}
        </div>
    );
}

// Toast Component
export function Toast({ message, type, onClose }: { message: string; type: 'success' | 'error' | 'info'; onClose: () => void }) {
    useEffect(() => {
        const timer = setTimeout(onClose, 5000);
        return () => clearTimeout(timer);
    }, []);
    
    return (
        <div className={\`toast toast-\${type}\`}>
            <span>{message}</span>
            <button onClick={onClose}>×</button>
        </div>
    );
}

// Avatar Component
export function Avatar({ src, name, size = 'md' }: { src?: string; name: string; size?: 'sm' | 'md' | 'lg' }) {
    const initials = name.split(' ').map(n => n[0]).join('').slice(0, 2);
    
    return src ? (
        <img src={src} alt={name} className={\`avatar avatar-\${size}\`} />
    ) : (
        <div className={\`avatar avatar-\${size} avatar-fallback\`}>{initials}</div>
    );
}

// Badge Component
export function Badge({ children, variant = 'default' }: { children: React.ReactNode; variant?: 'default' | 'success' | 'warning' | 'danger' }) {
    return <span className={\`badge badge-\${variant}\`}>{children}</span>;
}

export { Button, Input, Modal, Card, Toast, Avatar, Badge };
`;
    }
}

export const componentLibrary = ComponentLibrary.getInstance();
