/**
 * 📊 CostTrackerService
 * 
 * Cost tracking:
 * - API costs, budgets, alerts
 */

import { EventEmitter } from 'events';

export class CostTrackerService extends EventEmitter {
    private static instance: CostTrackerService;
    private constructor() { super(); }
    static getInstance(): CostTrackerService {
        if (!CostTrackerService.instance) {
            CostTrackerService.instance = new CostTrackerService();
        }
        return CostTrackerService.instance;
    }

    generate(): string {
        return `// Cost Tracker Service - API costs, budgets
// Generated by Shadow AI

class CostTracker {
    private usage: UsageEntry[] = [];
    private budgets: Map<string, Budget> = new Map();
    
    private pricing: Record<string, { input: number; output: number }> = {
        'gpt-4-turbo': { input: 0.01 / 1000, output: 0.03 / 1000 },
        'gpt-3.5-turbo': { input: 0.0005 / 1000, output: 0.0015 / 1000 },
        'claude-3-opus': { input: 0.015 / 1000, output: 0.075 / 1000 },
        'claude-3-sonnet': { input: 0.003 / 1000, output: 0.015 / 1000 },
        'text-embedding-3-small': { input: 0.00002 / 1000, output: 0 }
    };
    
    // Track usage
    track(model: string, inputTokens: number, outputTokens: number, metadata?: any): void {
        const price = this.pricing[model] || { input: 0.001, output: 0.002 };
        const cost = (inputTokens * price.input) + (outputTokens * price.output);
        
        this.usage.push({
            model,
            inputTokens,
            outputTokens,
            cost,
            timestamp: Date.now(),
            metadata
        });
        
        // Check budgets
        this.checkBudgets();
    }
    
    // Set budget
    setBudget(name: string, amount: number, period: 'daily' | 'weekly' | 'monthly'): void {
        this.budgets.set(name, {
            name,
            amount,
            period,
            createdAt: Date.now()
        });
    }
    
    // Get current spend
    getCurrentSpend(period: 'day' | 'week' | 'month' = 'month'): number {
        const startDate = this.getStartDate(period);
        
        return this.usage
            .filter(u => u.timestamp >= startDate.getTime())
            .reduce((sum, u) => sum + u.cost, 0);
    }
    
    // Get spend by model
    getSpendByModel(period: 'day' | 'week' | 'month' = 'month'): Record<string, number> {
        const startDate = this.getStartDate(period);
        const filtered = this.usage.filter(u => u.timestamp >= startDate.getTime());
        
        const byModel: Record<string, number> = {};
        
        for (const entry of filtered) {
            byModel[entry.model] = (byModel[entry.model] || 0) + entry.cost;
        }
        
        return byModel;
    }
    
    // Check budgets and emit alerts
    private checkBudgets(): void {
        for (const [name, budget] of this.budgets) {
            const spend = this.getCurrentSpend(
                budget.period === 'daily' ? 'day' : budget.period === 'weekly' ? 'week' : 'month'
            );
            
            if (spend >= budget.amount) {
                this.emit('budget-exceeded', { name, budget: budget.amount, spent: spend });
            } else if (spend >= budget.amount * 0.8) {
                this.emit('budget-warning', { name, budget: budget.amount, spent: spend, remaining: budget.amount - spend });
            }
        }
    }
    
    // Get usage report
    getReport(period: 'day' | 'week' | 'month'): UsageReport {
        const startDate = this.getStartDate(period);
        const filtered = this.usage.filter(u => u.timestamp >= startDate.getTime());
        
        return {
            period,
            totalCost: filtered.reduce((sum, u) => sum + u.cost, 0),
            totalInputTokens: filtered.reduce((sum, u) => sum + u.inputTokens, 0),
            totalOutputTokens: filtered.reduce((sum, u) => sum + u.outputTokens, 0),
            byModel: this.getSpendByModel(period),
            entries: filtered.length
        };
    }
    
    private getStartDate(period: 'day' | 'week' | 'month'): Date {
        const now = new Date();
        switch (period) {
            case 'day': return new Date(now.setHours(0, 0, 0, 0));
            case 'week': return new Date(now.setDate(now.getDate() - 7));
            case 'month': return new Date(now.setMonth(now.getMonth() - 1));
        }
    }
}

export { CostTracker };
`;
    }
}

export const costTrackerService = CostTrackerService.getInstance();
