/**
 * 📊 DataVisualizationGenerator
 * 
 * Data visualization:
 * - Charts, graphs, dashboards
 */

import { EventEmitter } from 'events';

export class DataVisualizationGenerator extends EventEmitter {
    private static instance: DataVisualizationGenerator;
    private constructor() { super(); }
    static getInstance(): DataVisualizationGenerator {
        if (!DataVisualizationGenerator.instance) {
            DataVisualizationGenerator.instance = new DataVisualizationGenerator();
        }
        return DataVisualizationGenerator.instance;
    }

    generate(): string {
        return `// Data Visualization Generator - Charts, graphs, dashboards
// Generated by Shadow AI

import { Chart, registerables } from 'chart.js';
import { Line, Bar, Pie, Doughnut, Radar, Scatter } from 'react-chartjs-2';

Chart.register(...registerables);

// Chart Components
export function LineChart({ data, options }: ChartProps) {
    return <Line data={data} options={{ responsive: true, ...options }} />;
}

export function BarChart({ data, options }: ChartProps) {
    return <Bar data={data} options={{ responsive: true, ...options }} />;
}

export function PieChart({ data, options }: ChartProps) {
    return <Pie data={data} options={{ responsive: true, ...options }} />;
}

// Dashboard Grid
export function DashboardGrid({ widgets }: { widgets: Widget[] }) {
    return (
        <div className="grid grid-cols-12 gap-4">
            {widgets.map(widget => (
                <div key={widget.id} className={\`col-span-\${widget.width || 6}\`}>
                    <WidgetCard widget={widget} />
                </div>
            ))}
        </div>
    );
}

// KPI Card
export function KPICard({ title, value, change, icon }: KPIProps) {
    const isPositive = change >= 0;
    
    return (
        <div className="kpi-card">
            <div className="kpi-icon">{icon}</div>
            <div className="kpi-content">
                <h3>{title}</h3>
                <div className="kpi-value">{value}</div>
                <div className={\`kpi-change \${isPositive ? 'positive' : 'negative'}\`}>
                    {isPositive ? '↑' : '↓'} {Math.abs(change)}%
                </div>
            </div>
        </div>
    );
}

// Data Table with Sorting
export function DataTable({ columns, data }: TableProps) {
    const [sortBy, setSortBy] = useState<string | null>(null);
    const [sortDir, setSortDir] = useState<'asc' | 'desc'>('asc');
    
    const sortedData = useMemo(() => {
        if (!sortBy) return data;
        return [...data].sort((a, b) => {
            const aVal = a[sortBy];
            const bVal = b[sortBy];
            const cmp = aVal < bVal ? -1 : aVal > bVal ? 1 : 0;
            return sortDir === 'asc' ? cmp : -cmp;
        });
    }, [data, sortBy, sortDir]);
    
    return (
        <table>
            <thead>
                <tr>
                    {columns.map(col => (
                        <th key={col.key} onClick={() => {
                            if (sortBy === col.key) setSortDir(d => d === 'asc' ? 'desc' : 'asc');
                            else { setSortBy(col.key); setSortDir('asc'); }
                        }}>
                            {col.label} {sortBy === col.key && (sortDir === 'asc' ? '↑' : '↓')}
                        </th>
                    ))}
                </tr>
            </thead>
            <tbody>
                {sortedData.map((row, i) => (
                    <tr key={i}>
                        {columns.map(col => <td key={col.key}>{row[col.key]}</td>)}
                    </tr>
                ))}
            </tbody>
        </table>
    );
}

export { LineChart, BarChart, PieChart, DashboardGrid, KPICard, DataTable };
`;
    }
}

export const dataVisualizationGenerator = DataVisualizationGenerator.getInstance();
