/**
 * 🦕 Deno Patterns Generator
 * 
 * Generate Deno applications:
 * - Fresh, Oak, native APIs
 */

import { EventEmitter } from 'events';

export class DenoPatterns extends EventEmitter {
    private static instance: DenoPatterns;

    private constructor() { super(); }

    static getInstance(): DenoPatterns {
        if (!DenoPatterns.instance) {
            DenoPatterns.instance = new DenoPatterns();
        }
        return DenoPatterns.instance;
    }

    generateFresh(): string {
        return `// Deno Fresh Application
// Generated by Shadow AI

// deno.json
{
    "lock": false,
    "tasks": {
        "check": "deno fmt --check && deno lint && deno check **/*.ts && deno check **/*.tsx",
        "start": "deno run -A --watch=static/,routes/ dev.ts",
        "build": "deno run -A dev.ts build",
        "preview": "deno run -A main.ts"
    },
    "imports": {
        "$fresh/": "https://deno.land/x/fresh@1.6.0/",
        "preact": "https://esm.sh/preact@10.19.2",
        "preact/": "https://esm.sh/preact@10.19.2/",
        "@preact/signals": "https://esm.sh/*@preact/signals@1.2.1",
        "@preact/signals-core": "https://esm.sh/*@preact/signals-core@1.5.0"
    },
    "compilerOptions": {
        "jsx": "react-jsx",
        "jsxImportSource": "preact"
    }
}

// routes/_app.tsx
import { type PageProps } from "$fresh/server.ts";

export default function App({ Component }: PageProps) {
    return (
        <html>
            <head>
                <meta charset="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <title>Fresh App</title>
                <link rel="stylesheet" href="/styles.css" />
            </head>
            <body>
                <Component />
            </body>
        </html>
    );
}

// routes/index.tsx
import { Handlers, PageProps } from "$fresh/server.ts";

interface Data {
    posts: { id: string; title: string }[];
}

export const handler: Handlers<Data> = {
    async GET(_req, ctx) {
        const posts = await db.query("SELECT id, title FROM posts ORDER BY created_at DESC LIMIT 10");
        return ctx.render({ posts });
    }
};

export default function Home({ data }: PageProps<Data>) {
    return (
        <div>
            <h1>Welcome to Fresh</h1>
            <ul>
                {data.posts.map(post => (
                    <li key={post.id}>
                        <a href={\`/posts/\${post.id}\`}>{post.title}</a>
                    </li>
                ))}
            </ul>
        </div>
    );
}

// routes/api/posts.ts
import { Handlers } from "$fresh/server.ts";

export const handler: Handlers = {
    async GET() {
        const posts = await db.query("SELECT * FROM posts");
        return new Response(JSON.stringify(posts), {
            headers: { "Content-Type": "application/json" }
        });
    },
    
    async POST(req) {
        const body = await req.json();
        const post = await db.query("INSERT INTO posts (title, content) VALUES ($1, $2) RETURNING *", [body.title, body.content]);
        return new Response(JSON.stringify(post), { status: 201 });
    }
};

// islands/Counter.tsx (Interactive Component)
import { useSignal } from "@preact/signals";

export default function Counter() {
    const count = useSignal(0);
    
    return (
        <div>
            <p>Count: {count}</p>
            <button onClick={() => count.value++}>Increment</button>
        </div>
    );
}
`;
    }

    generateOak(): string {
        return `// Deno Oak Server
// Generated by Shadow AI

import { Application, Router, Context, send } from "https://deno.land/x/oak/mod.ts";
import { oakCors } from "https://deno.land/x/cors/mod.ts";

const app = new Application();
const router = new Router();

// Middleware
app.use(oakCors());
app.use(async (ctx, next) => {
    const start = Date.now();
    await next();
    const ms = Date.now() - start;
    ctx.response.headers.set("X-Response-Time", \`\${ms}ms\`);
    console.log(\`\${ctx.request.method} \${ctx.request.url} - \${ms}ms\`);
});

// Error handling
app.use(async (ctx, next) => {
    try {
        await next();
    } catch (err) {
        ctx.response.status = err.status || 500;
        ctx.response.body = { error: err.message };
    }
});

// Routes
router.get("/", (ctx) => {
    ctx.response.body = { message: "Hello from Deno!" };
});

router.get("/api/users", async (ctx) => {
    const users = await db.query("SELECT * FROM users");
    ctx.response.body = users;
});

router.get("/api/users/:id", async (ctx) => {
    const { id } = ctx.params;
    const user = await db.queryObject("SELECT * FROM users WHERE id = $1", [id]);
    if (!user) {
        ctx.throw(404, "User not found");
    }
    ctx.response.body = user;
});

router.post("/api/users", async (ctx) => {
    const body = await ctx.request.body().value;
    const user = await db.queryObject(
        "INSERT INTO users (name, email) VALUES ($1, $2) RETURNING *",
        [body.name, body.email]
    );
    ctx.response.status = 201;
    ctx.response.body = user;
});

// Static files
app.use(async (ctx, next) => {
    try {
        await send(ctx, ctx.request.url.pathname, {
            root: \`\${Deno.cwd()}/static\`,
            index: "index.html"
        });
    } catch {
        await next();
    }
});

app.use(router.routes());
app.use(router.allowedMethods());

console.log("Server running on http://localhost:8000");
await app.listen({ port: 8000 });
`;
    }

    generateNative(): string {
        return `// Deno Native APIs
// Generated by Shadow AI

// File System
async function readFile(path: string): Promise<string> {
    return await Deno.readTextFile(path);
}

async function writeFile(path: string, content: string): Promise<void> {
    await Deno.writeTextFile(path, content);
}

async function listDir(path: string): Promise<string[]> {
    const entries = [];
    for await (const entry of Deno.readDir(path)) {
        entries.push(entry.name);
    }
    return entries;
}

// HTTP Server
Deno.serve({ port: 8000 }, async (request) => {
    const url = new URL(request.url);
    
    if (url.pathname === "/") {
        return new Response("Hello, World!");
    }
    
    if (url.pathname === "/api/data") {
        return Response.json({ data: "value" });
    }
    
    return new Response("Not Found", { status: 404 });
});

// Environment
const apiKey = Deno.env.get("API_KEY");

// Subprocess
const command = new Deno.Command("git", {
    args: ["status"],
    stdout: "piped"
});
const { stdout } = await command.output();
console.log(new TextDecoder().decode(stdout));

// WebSocket Server
Deno.serve({ port: 8080 }, (request) => {
    if (request.headers.get("upgrade") === "websocket") {
        const { socket, response } = Deno.upgradeWebSocket(request);
        
        socket.onopen = () => console.log("Connected");
        socket.onmessage = (e) => {
            socket.send(\`Echo: \${e.data}\`);
        };
        socket.onclose = () => console.log("Disconnected");
        
        return response;
    }
    
    return new Response("Not a websocket request", { status: 400 });
});
`;
    }
}

export const denoPatterns = DenoPatterns.getInstance();
