/**
 * 🐳 Docker Generator
 * 
 * Generate Docker configurations:
 * - Dockerfile, docker-compose
 * - Multi-stage builds
 */

import { EventEmitter } from 'events';

export type AppType = 'node' | 'python' | 'go' | 'rust' | 'java' | 'static';

export class DockerGenerator extends EventEmitter {
    private static instance: DockerGenerator;

    private constructor() { super(); }

    static getInstance(): DockerGenerator {
        if (!DockerGenerator.instance) {
            DockerGenerator.instance = new DockerGenerator();
        }
        return DockerGenerator.instance;
    }

    generateDockerfile(appType: AppType): string {
        switch (appType) {
            case 'node': return this.nodeDockerfile();
            case 'python': return this.pythonDockerfile();
            case 'go': return this.goDockerfile();
            case 'rust': return this.rustDockerfile();
            case 'static': return this.staticDockerfile();
            default: return this.nodeDockerfile();
        }
    }

    private nodeDockerfile(): string {
        return `# Node.js Dockerfile (Multi-stage)
# Generated by Shadow AI

# Build stage
FROM node:20-alpine AS builder
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Build
COPY . .
RUN npm run build

# Prune dev dependencies
RUN npm prune --production

# Production stage
FROM node:20-alpine AS runner
WORKDIR /app

# Security: non-root user
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 appuser

# Copy built assets
COPY --from=builder --chown=appuser:nodejs /app/dist ./dist
COPY --from=builder --chown=appuser:nodejs /app/node_modules ./node_modules
COPY --from=builder --chown=appuser:nodejs /app/package.json ./

USER appuser

EXPOSE 3000
ENV NODE_ENV=production

CMD ["node", "dist/index.js"]
`;
    }

    private pythonDockerfile(): string {
        return `# Python Dockerfile
# Generated by Shadow AI

FROM python:3.11-slim AS builder

WORKDIR /app
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

FROM python:3.11-slim

WORKDIR /app

RUN useradd --create-home appuser
COPY --from=builder /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY --chown=appuser:appuser . .

USER appuser

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
`;
    }

    private goDockerfile(): string {
        return `# Go Dockerfile
# Generated by Shadow AI

FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /app/server .

FROM scratch

COPY --from=builder /app/server /server
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

EXPOSE 8080

ENTRYPOINT ["/server"]
`;
    }

    private rustDockerfile(): string {
        return `# Rust Dockerfile
# Generated by Shadow AI

FROM rust:1.75-alpine AS builder

RUN apk add --no-cache musl-dev

WORKDIR /app
COPY . .

RUN cargo build --release --target x86_64-unknown-linux-musl

FROM scratch

COPY --from=builder /app/target/x86_64-unknown-linux-musl/release/app /app

EXPOSE 8080

ENTRYPOINT ["/app"]
`;
    }

    private staticDockerfile(): string {
        return `# Static Site Dockerfile
# Generated by Shadow AI

FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
`;
    }

    generateDockerCompose(services: string[]): string {
        let compose = `# Docker Compose
# Generated by Shadow AI

version: '3.8'

services:
`;
        if (services.includes('app')) {
            compose += `  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    restart: unless-stopped

`;
        }

        if (services.includes('db') || services.includes('postgres')) {
            compose += `  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

`;
        }

        if (services.includes('redis')) {
            compose += `  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

`;
        }

        if (services.includes('nginx')) {
            compose += `  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - app

`;
        }

        compose += `volumes:
`;
        if (services.includes('db') || services.includes('postgres')) {
            compose += `  postgres_data:\n`;
        }
        if (services.includes('redis')) {
            compose += `  redis_data:\n`;
        }

        return compose;
    }

    generateNginxConf(): string {
        return `# Nginx Configuration
# Generated by Shadow AI

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Logging
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # Gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript;

    # Rate limiting
    limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;

    upstream app {
        server app:3000;
    }

    server {
        listen 80;
        server_name _;

        # Redirect to HTTPS
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl http2;
        server_name _;

        ssl_certificate /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/key.pem;

        # Security headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;

        location / {
            proxy_pass http://app;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cache_bypass $http_upgrade;
        }

        location /api {
            limit_req zone=api burst=20 nodelay;
            proxy_pass http://app;
        }
    }
}
`;
    }
}

export const dockerGenerator = DockerGenerator.getInstance();
