/**
 * 📧 Email Template Generator
 * 
 * Email marketing templates:
 * - Responsive, transactional, marketing
 */

import { EventEmitter } from 'events';

export class EmailTemplateGenerator extends EventEmitter {
    private static instance: EmailTemplateGenerator;

    private constructor() { super(); }

    static getInstance(): EmailTemplateGenerator {
        if (!EmailTemplateGenerator.instance) {
            EmailTemplateGenerator.instance = new EmailTemplateGenerator();
        }
        return EmailTemplateGenerator.instance;
    }

    generate(): string {
        return `// Email Template Generator
// Generated by Shadow AI

/**
 * EMAIL TEMPLATE GENERATOR
 * 
 * Generate responsive email templates for all email clients.
 */

interface EmailTemplate {
    name: string;
    subject: string;
    preheader: string;
    html: string;
    text: string;
    variables: string[];
}

// === Template Generator ===
class TemplateGenerator {
    generateWelcomeEmail(brand: BrandConfig): EmailTemplate {
        return {
            name: 'welcome',
            subject: 'Welcome to {{brand_name}}!',
            preheader: 'Thanks for signing up. Here\\'s what\\'s next...',
            variables: ['user_name', 'brand_name', 'login_url'],
            html: \`
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to \${brand.name}</title>
    <style>
        body { margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }
        .container { max-width: 600px; margin: 0 auto; }
        .header { background: \${brand.primaryColor}; padding: 40px 20px; text-align: center; }
        .header img { max-width: 150px; }
        .content { padding: 40px 20px; background: #ffffff; }
        .button { display: inline-block; padding: 14px 28px; background: \${brand.primaryColor}; color: #ffffff; text-decoration: none; border-radius: 6px; font-weight: bold; }
        .footer { padding: 20px; text-align: center; color: #666; font-size: 12px; }
        
        @media only screen and (max-width: 600px) {
            .container { width: 100% !important; }
            .content { padding: 20px !important; }
        }
    </style>
</head>
<body style="background: #f4f4f4;">
    <table class="container" cellpadding="0" cellspacing="0" width="100%">
        <tr>
            <td class="header">
                <img src="\${brand.logoUrl}" alt="\${brand.name}">
            </td>
        </tr>
        <tr>
            <td class="content">
                <h1 style="color: #333; margin: 0 0 20px;">Welcome, {{user_name}}! 🎉</h1>
                <p style="color: #666; line-height: 1.6; margin: 0 0 20px;">
                    Thanks for joining {{brand_name}}. We're excited to have you on board!
                </p>
                <p style="color: #666; line-height: 1.6; margin: 0 0 30px;">
                    Click the button below to get started:
                </p>
                <p style="text-align: center; margin: 0 0 30px;">
                    <a href="{{login_url}}" class="button">Get Started</a>
                </p>
                <p style="color: #666; line-height: 1.6; margin: 0;">
                    If you have any questions, just reply to this email. We're here to help!
                </p>
            </td>
        </tr>
        <tr>
            <td class="footer">
                <p>&copy; {{current_year}} {{brand_name}}. All rights reserved.</p>
                <p>
                    <a href="{{unsubscribe_url}}" style="color: #666;">Unsubscribe</a> | 
                    <a href="{{preferences_url}}" style="color: #666;">Email Preferences</a>
                </p>
            </td>
        </tr>
    </table>
</body>
</html>
            \`,
            text: \`
Welcome, {{user_name}}!

Thanks for joining {{brand_name}}. We're excited to have you on board!

Get started: {{login_url}}

If you have any questions, just reply to this email.

---
© {{current_year}} {{brand_name}}
Unsubscribe: {{unsubscribe_url}}
            \`
        };
    }
    
    generateTransactionalEmail(type: 'order_confirmation' | 'password_reset' | 'invoice'): EmailTemplate {
        const templates = {
            order_confirmation: {
                name: 'order_confirmation',
                subject: 'Order Confirmed - #{{order_id}}',
                preheader: 'Your order has been confirmed and is being processed.',
                variables: ['order_id', 'items', 'total', 'shipping_address']
            },
            password_reset: {
                name: 'password_reset',
                subject: 'Reset Your Password',
                preheader: 'Click the link below to reset your password.',
                variables: ['user_name', 'reset_url', 'expiry_time']
            },
            invoice: {
                name: 'invoice',
                subject: 'Invoice #{{invoice_id}} from {{brand_name}}',
                preheader: 'Your invoice is ready.',
                variables: ['invoice_id', 'amount', 'due_date', 'items', 'payment_url']
            }
        };
        
        return templates[type];
    }
}

// === React Email Generator ===
class ReactEmailGenerator {
    generateComponent(template: EmailTemplate): string {
        return \`
// \${template.name}.tsx - React Email Template
import {
    Body,
    Button,
    Container,
    Head,
    Heading,
    Html,
    Img,
    Link,
    Preview,
    Section,
    Text,
} from '@react-email/components';

interface Props {
    \${template.variables.map(v => \`\${v}: string;\`).join('\\n    ')}
}

export default function \${this.capitalize(template.name)}Email(props: Props) {
    return (
        <Html>
            <Head />
            <Preview>\${template.preheader}</Preview>
            <Body style={main}>
                <Container style={container}>
                    <Section style={header}>
                        <Img src={logo} alt="Logo" width="150" />
                    </Section>
                    <Section style={content}>
                        <Heading style={h1}>Welcome, {props.user_name}!</Heading>
                        <Text style={text}>
                            Thanks for joining us. We're excited to have you on board!
                        </Text>
                        <Button style={button} href={props.login_url}>
                            Get Started
                        </Button>
                    </Section>
                    <Section style={footer}>
                        <Text style={footerText}>
                            © 2024 Company Name. All rights reserved.
                        </Text>
                    </Section>
                </Container>
            </Body>
        </Html>
    );
}

const main = { backgroundColor: '#f4f4f4', fontFamily: 'sans-serif' };
const container = { maxWidth: '600px', margin: '0 auto' };
const header = { backgroundColor: '#6366f1', padding: '40px 20px', textAlign: 'center' as const };
const content = { padding: '40px 20px', backgroundColor: '#ffffff' };
const h1 = { color: '#333', marginBottom: '20px' };
const text = { color: '#666', lineHeight: '1.6' };
const button = { backgroundColor: '#6366f1', color: '#fff', padding: '14px 28px', borderRadius: '6px' };
const footer = { padding: '20px', textAlign: 'center' as const };
const footerText = { color: '#666', fontSize: '12px' };
        \`;
    }
}

export { TemplateGenerator, ReactEmailGenerator };
`;
    }
}

export const emailTemplateGenerator = EmailTemplateGenerator.getInstance();
