/**
 * 📤 FileExportGenerator
 * 
 * File exports:
 * - CSV, Excel, PDF, JSON
 */

import { EventEmitter } from 'events';

export class FileExportGenerator extends EventEmitter {
    private static instance: FileExportGenerator;
    private constructor() { super(); }
    static getInstance(): FileExportGenerator {
        if (!FileExportGenerator.instance) {
            FileExportGenerator.instance = new FileExportGenerator();
        }
        return FileExportGenerator.instance;
    }

    generate(): string {
        return `// File Export Generator - CSV, Excel, PDF, JSON
// Generated by Shadow AI

import ExcelJS from 'exceljs';
import { parse } from 'json2csv';

class FileExportService {
    // CSV Export
    async exportCSV(data: any[], fields: string[]): Promise<string> {
        return parse(data, { fields });
    }
    
    // Excel Export
    async exportExcel(data: any[], columns: { header: string; key: string }[]): Promise<Buffer> {
        const workbook = new ExcelJS.Workbook();
        const worksheet = workbook.addWorksheet('Data');
        
        worksheet.columns = columns;
        worksheet.addRows(data);
        
        // Style header row
        worksheet.getRow(1).font = { bold: true };
        worksheet.getRow(1).fill = {
            type: 'pattern',
            pattern: 'solid',
            fgColor: { argb: 'FFE0E0E0' }
        };
        
        return workbook.xlsx.writeBuffer() as Promise<Buffer>;
    }
    
    // JSON Export
    exportJSON(data: any[], pretty = true): string {
        return pretty ? JSON.stringify(data, null, 2) : JSON.stringify(data);
    }
    
    // PDF Export (using Puppeteer)
    async exportPDF(html: string): Promise<Buffer> {
        const puppeteer = require('puppeteer');
        const browser = await puppeteer.launch({ headless: 'new' });
        const page = await browser.newPage();
        
        await page.setContent(html);
        const pdf = await page.pdf({ format: 'A4', printBackground: true });
        
        await browser.close();
        return pdf;
    }
}

// Express Routes
function setupExportRoutes(app: Express, getData: () => Promise<any[]>) {
    app.get('/export/csv', async (req, res) => {
        const data = await getData();
        const csv = await exportService.exportCSV(data, Object.keys(data[0] || {}));
        
        res.setHeader('Content-Type', 'text/csv');
        res.setHeader('Content-Disposition', 'attachment; filename="export.csv"');
        res.send(csv);
    });
    
    app.get('/export/excel', async (req, res) => {
        const data = await getData();
        const columns = Object.keys(data[0] || {}).map(key => ({ header: key, key }));
        const excel = await exportService.exportExcel(data, columns);
        
        res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        res.setHeader('Content-Disposition', 'attachment; filename="export.xlsx"');
        res.send(excel);
    });
    
    app.get('/export/json', async (req, res) => {
        const data = await getData();
        const json = exportService.exportJSON(data);
        
        res.setHeader('Content-Type', 'application/json');
        res.setHeader('Content-Disposition', 'attachment; filename="export.json"');
        res.send(json);
    });
}

// React Export Button
export function ExportButton({ data, filename }: { data: any[]; filename: string }) {
    const [exporting, setExporting] = useState(false);
    
    const exportAs = async (format: 'csv' | 'json' | 'excel') => {
        setExporting(true);
        
        const response = await fetch(\`/export/\${format}\`);
        const blob = await response.blob();
        
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = \`\${filename}.\${format === 'excel' ? 'xlsx' : format}\`;
        a.click();
        
        setExporting(false);
    };
    
    return (
        <div className="export-menu">
            <button onClick={() => exportAs('csv')} disabled={exporting}>Export CSV</button>
            <button onClick={() => exportAs('excel')} disabled={exporting}>Export Excel</button>
            <button onClick={() => exportAs('json')} disabled={exporting}>Export JSON</button>
        </div>
    );
}

export { FileExportService, setupExportRoutes, ExportButton };
`;
    }
}

export const fileExportGenerator = FileExportGenerator.getInstance();
