/**
 * 📥 FileImportGenerator
 * 
 * File imports:
 * - CSV, Excel, JSON parsing
 */

import { EventEmitter } from 'events';

export class FileImportGenerator extends EventEmitter {
    private static instance: FileImportGenerator;
    private constructor() { super(); }
    static getInstance(): FileImportGenerator {
        if (!FileImportGenerator.instance) {
            FileImportGenerator.instance = new FileImportGenerator();
        }
        return FileImportGenerator.instance;
    }

    generate(): string {
        return `// File Import Generator - CSV, Excel, JSON parsing
// Generated by Shadow AI

import { parse as parseCSV } from 'csv-parse';
import ExcelJS from 'exceljs';

class FileImportService {
    // CSV Import
    async importCSV(content: string | Buffer): Promise<any[]> {
        return new Promise((resolve, reject) => {
            const records: any[] = [];
            
            const parser = parseCSV(content, {
                columns: true,
                skip_empty_lines: true,
                trim: true
            });
            
            parser.on('readable', () => {
                let record;
                while ((record = parser.read()) !== null) {
                    records.push(record);
                }
            });
            
            parser.on('error', reject);
            parser.on('end', () => resolve(records));
        });
    }
    
    // Excel Import
    async importExcel(buffer: Buffer): Promise<any[]> {
        const workbook = new ExcelJS.Workbook();
        await workbook.xlsx.load(buffer);
        
        const worksheet = workbook.worksheets[0];
        const data: any[] = [];
        
        const headers: string[] = [];
        worksheet.getRow(1).eachCell((cell, colNumber) => {
            headers[colNumber - 1] = cell.value?.toString() || '';
        });
        
        worksheet.eachRow((row, rowNumber) => {
            if (rowNumber === 1) return;
            
            const record: any = {};
            row.eachCell((cell, colNumber) => {
                record[headers[colNumber - 1]] = cell.value;
            });
            data.push(record);
        });
        
        return data;
    }
    
    // JSON Import
    importJSON(content: string): any[] {
        return JSON.parse(content);
    }
    
    // Validate imported data
    validate(data: any[], schema: ValidationSchema): ValidationResult {
        const errors: ValidationError[] = [];
        
        data.forEach((row, index) => {
            for (const [field, rules] of Object.entries(schema)) {
                const value = row[field];
                
                if (rules.required && !value) {
                    errors.push({ row: index + 1, field, error: 'Required field' });
                }
                
                if (rules.type === 'number' && isNaN(Number(value))) {
                    errors.push({ row: index + 1, field, error: 'Must be a number' });
                }
                
                if (rules.type === 'email' && !this.isValidEmail(value)) {
                    errors.push({ row: index + 1, field, error: 'Invalid email' });
                }
            }
        });
        
        return { valid: errors.length === 0, errors };
    }
    
    private isValidEmail(email: string): boolean {
        return /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(email);
    }
}

// React Import Component
export function FileImporter({ onImport, accept }: { onImport: (data: any[]) => void; accept: string[] }) {
    const [importing, setImporting] = useState(false);
    const [error, setError] = useState<string | null>(null);
    
    const handleFile = async (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (!file) return;
        
        setImporting(true);
        setError(null);
        
        try {
            const formData = new FormData();
            formData.append('file', file);
            
            const response = await fetch('/api/import', {
                method: 'POST',
                body: formData
            });
            
            const data = await response.json();
            onImport(data);
        } catch (err) {
            setError(err.message);
        }
        
        setImporting(false);
    };
    
    return (
        <div className="file-importer">
            <input type="file" accept={accept.join(',')} onChange={handleFile} disabled={importing} />
            {importing && <span>Importing...</span>}
            {error && <span className="error">{error}</span>}
        </div>
    );
}

export { FileImportService, FileImporter };
`;
    }
}

export const fileImportGenerator = FileImportGenerator.getInstance();
