/**
 * 💰 InvoiceGenerator
 * 
 * Invoicing system:
 * - Invoices, payments, PDF
 */

import { EventEmitter } from 'events';

export class InvoiceGenerator extends EventEmitter {
    private static instance: InvoiceGenerator;
    private constructor() { super(); }
    static getInstance(): InvoiceGenerator {
        if (!InvoiceGenerator.instance) {
            InvoiceGenerator.instance = new InvoiceGenerator();
        }
        return InvoiceGenerator.instance;
    }

    generate(): string {
        return `// Invoice Generator - Invoices, payments, PDF
// Generated by Shadow AI

// Invoice Schema
model Invoice {
    id          String   @id @default(cuid())
    number      String   @unique
    customerId  String
    customer    Customer @relation(fields: [customerId], references: [id])
    items       InvoiceItem[]
    subtotal    Float
    tax         Float
    total       Float
    currency    String   @default("USD")
    status      InvoiceStatus @default(DRAFT)
    dueDate     DateTime
    paidAt      DateTime?
    notes       String?
    createdAt   DateTime @default(now())
}

model InvoiceItem {
    id          String   @id @default(cuid())
    description String
    quantity    Int
    unitPrice   Float
    total       Float
    invoiceId   String
    invoice     Invoice  @relation(fields: [invoiceId], references: [id])
}

enum InvoiceStatus {
    DRAFT
    SENT
    PAID
    OVERDUE
    CANCELLED
}

// Invoice Service
class InvoiceService {
    async createInvoice(data: CreateInvoiceData) {
        const number = await this.generateInvoiceNumber();
        const items = data.items.map(item => ({
            ...item,
            total: item.quantity * item.unitPrice
        }));
        
        const subtotal = items.reduce((sum, item) => sum + item.total, 0);
        const tax = subtotal * (data.taxRate || 0);
        const total = subtotal + tax;
        
        return prisma.invoice.create({
            data: {
                number,
                customerId: data.customerId,
                items: { createMany: { data: items } },
                subtotal,
                tax,
                total,
                dueDate: data.dueDate,
                notes: data.notes
            },
            include: { items: true, customer: true }
        });
    }
    
    async sendInvoice(id: string) {
        const invoice = await prisma.invoice.update({
            where: { id },
            data: { status: 'SENT' },
            include: { customer: true, items: true }
        });
        
        const pdf = await this.generatePDF(invoice);
        
        await sendEmail({
            to: invoice.customer.email,
            subject: \`Invoice #\${invoice.number}\`,
            body: \`Please find attached invoice #\${invoice.number}\`,
            attachments: [{ filename: \`invoice-\${invoice.number}.pdf\`, content: pdf }]
        });
        
        return invoice;
    }
    
    async markAsPaid(id: string) {
        return prisma.invoice.update({
            where: { id },
            data: { status: 'PAID', paidAt: new Date() }
        });
    }
    
    async generatePDF(invoice: Invoice): Promise<Buffer> {
        const html = this.renderInvoiceTemplate(invoice);
        
        const browser = await puppeteer.launch({ headless: 'new' });
        const page = await browser.newPage();
        await page.setContent(html);
        const pdf = await page.pdf({ format: 'A4' });
        await browser.close();
        
        return pdf;
    }
    
    private async generateInvoiceNumber(): Promise<string> {
        const count = await prisma.invoice.count();
        const year = new Date().getFullYear();
        return \`INV-\${year}-\${String(count + 1).padStart(5, '0')}\`;
    }
}

// Invoice Component
export function InvoicePreview({ invoice }: { invoice: Invoice }) {
    return (
        <div className="invoice-preview">
            <div className="invoice-header">
                <h1>Invoice #{invoice.number}</h1>
                <Badge variant={invoice.status === 'PAID' ? 'success' : 'default'}>
                    {invoice.status}
                </Badge>
            </div>
            
            <table className="invoice-items">
                <thead>
                    <tr><th>Description</th><th>Qty</th><th>Price</th><th>Total</th></tr>
                </thead>
                <tbody>
                    {invoice.items.map(item => (
                        <tr key={item.id}>
                            <td>{item.description}</td>
                            <td>{item.quantity}</td>
                            <td>{formatCurrency(item.unitPrice)}</td>
                            <td>{formatCurrency(item.total)}</td>
                        </tr>
                    ))}
                </tbody>
            </table>
            
            <div className="invoice-totals">
                <div>Subtotal: {formatCurrency(invoice.subtotal)}</div>
                <div>Tax: {formatCurrency(invoice.tax)}</div>
                <div className="total">Total: {formatCurrency(invoice.total)}</div>
            </div>
        </div>
    );
}

export { InvoiceService, InvoicePreview };
`;
    }
}

export const invoiceGenerator = InvoiceGenerator.getInstance();
