/**
 * ☸️ Kubernetes Generator
 * 
 * Generate K8s manifests:
 * - Deployments, Services, Ingress
 */

import { EventEmitter } from 'events';

export class KubernetesGenerator extends EventEmitter {
    private static instance: KubernetesGenerator;

    private constructor() { super(); }

    static getInstance(): KubernetesGenerator {
        if (!KubernetesGenerator.instance) {
            KubernetesGenerator.instance = new KubernetesGenerator();
        }
        return KubernetesGenerator.instance;
    }

    generateDeployment(appName: string, image: string, replicas = 3): string {
        return `# Kubernetes Deployment
# Generated by Shadow AI

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${appName}
  labels:
    app: ${appName}
spec:
  replicas: ${replicas}
  selector:
    matchLabels:
      app: ${appName}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ${appName}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
    spec:
      serviceAccountName: ${appName}
      containers:
        - name: ${appName}
          image: ${image}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ${appName}-secrets
                  key: database-url
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - ${appName}
                topologyKey: kubernetes.io/hostname
`;
    }

    generateService(appName: string): string {
        return `# Kubernetes Service
apiVersion: v1
kind: Service
metadata:
  name: ${appName}
  labels:
    app: ${appName}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: ${appName}
`;
    }

    generateIngress(appName: string, domain: string): string {
        return `# Kubernetes Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${appName}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  tls:
    - hosts:
        - ${domain}
      secretName: ${appName}-tls
  rules:
    - host: ${domain}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${appName}
                port:
                  number: 80
`;
    }

    generateHPA(appName: string): string {
        return `# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${appName}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${appName}
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
`;
    }

    generateConfigMapAndSecret(appName: string): string {
        return `# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${appName}-config
data:
  LOG_LEVEL: "info"
  API_TIMEOUT: "30000"

---
# Secret (base64 encoded values)
apiVersion: v1
kind: Secret
metadata:
  name: ${appName}-secrets
type: Opaque
data:
  database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc0Bob3N0OjU0MzIvZGI=
  jwt-secret: c2VjcmV0LWtleS1oZXJl
`;
    }

    generateFullStack(appName: string, image: string, domain: string): string {
        return `${this.generateDeployment(appName, image)}
---
${this.generateService(appName)}
---
${this.generateIngress(appName, domain)}
---
${this.generateHPA(appName)}
---
${this.generateConfigMapAndSecret(appName)}
`;
    }
}

export const kubernetesGenerator = KubernetesGenerator.getInstance();
