/**
 * 🎯 LandingPageBuilder
 * 
 * Marketing pages:
 * - Hero, features, pricing, CTA
 */

import { EventEmitter } from 'events';

export class LandingPageBuilder extends EventEmitter {
    private static instance: LandingPageBuilder;

    private constructor() { super(); }

    static getInstance(): LandingPageBuilder {
        if (!LandingPageBuilder.instance) {
            LandingPageBuilder.instance = new LandingPageBuilder();
        }
        return LandingPageBuilder.instance;
    }

    generate(): string {
        return `// Landing Page Builder
// Generated by Shadow AI

/**
 * LANDING PAGE BUILDER
 * 
 * Marketing landing pages with hero, features, pricing.
 */

// === Hero Section ===
const heroTemplates = {
    centered: \`
<section className="hero hero--centered">
    <div className="container">
        <span className="hero-badge">New Release</span>
        <h1 className="hero-title">
            Build amazing products<br />
            <span className="gradient-text">10x faster</span>
        </h1>
        <p className="hero-subtitle">
            The all-in-one platform for developers to build, deploy, and scale applications.
        </p>
        <div className="hero-cta">
            <button className="btn btn-primary btn-lg">Get Started Free</button>
            <button className="btn btn-outline btn-lg">Watch Demo</button>
        </div>
        <div className="hero-social-proof">
            <div className="avatars">
                {/* User avatars */}
            </div>
            <span>Join 10,000+ developers</span>
        </div>
    </div>
</section>
    \`,
    
    splitImage: \`
<section className="hero hero--split">
    <div className="container">
        <div className="hero-content">
            <h1>Transform your workflow</h1>
            <p>Streamline your development process with our powerful tools.</p>
            <button className="btn btn-primary">Start Building</button>
        </div>
        <div className="hero-image">
            <img src="/hero-dashboard.png" alt="Dashboard" />
        </div>
    </div>
</section>
    \`
};

// === Features Section ===
const featureTemplates = {
    grid: \`
<section className="features">
    <div className="container">
        <div className="section-header">
            <h2>Everything you need</h2>
            <p>Powerful features to supercharge your development</p>
        </div>
        <div className="features-grid">
            {features.map(feature => (
                <div key={feature.id} className="feature-card">
                    <div className="feature-icon">{feature.icon}</div>
                    <h3>{feature.title}</h3>
                    <p>{feature.description}</p>
                </div>
            ))}
        </div>
    </div>
</section>
    \`,
    
    bento: \`
<section className="features features--bento">
    <div className="bento-grid">
        <div className="bento-item bento-item--large">
            <h3>AI-Powered Development</h3>
            <p>Let AI write, review, and optimize your code.</p>
            <div className="bento-visual">
                {/* Animation or image */}
            </div>
        </div>
        <div className="bento-item">
            <h3>Real-time Collaboration</h3>
            <p>Work together seamlessly.</p>
        </div>
        <div className="bento-item">
            <h3>One-Click Deploy</h3>
            <p>Deploy to production instantly.</p>
        </div>
    </div>
</section>
    \`
};

// === Pricing Section ===
const pricingTemplate = \`
<section className="pricing">
    <div className="container">
        <div className="section-header">
            <h2>Simple, transparent pricing</h2>
            <p>No hidden fees. Cancel anytime.</p>
        </div>
        
        <div className="pricing-toggle">
            <span>Monthly</span>
            <Toggle checked={annual} onChange={setAnnual} />
            <span>Annual (Save 20%)</span>
        </div>
        
        <div className="pricing-cards">
            {plans.map(plan => (
                <div key={plan.id} className={\\\`pricing-card \\\${plan.popular ? 'popular' : ''}\\\`}>
                    {plan.popular && <span className="popular-badge">Most Popular</span>}
                    <h3>{plan.name}</h3>
                    <div className="price">
                        <span className="amount">\${annual ? plan.annualPrice : plan.monthlyPrice}</span>
                        <span className="period">/month</span>
                    </div>
                    <p className="plan-description">{plan.description}</p>
                    <ul className="features-list">
                        {plan.features.map(f => (
                            <li key={f}><Check /> {f}</li>
                        ))}
                    </ul>
                    <button className={plan.popular ? 'btn btn-primary' : 'btn btn-outline'}>
                        {plan.cta}
                    </button>
                </div>
            ))}
        </div>
    </div>
</section>
\`;

// === Testimonials ===
const testimonialsTemplate = \`
<section className="testimonials">
    <div className="container">
        <h2>Loved by developers worldwide</h2>
        <div className="testimonials-grid">
            {testimonials.map(t => (
                <div key={t.id} className="testimonial-card">
                    <div className="stars">★★★★★</div>
                    <p className="quote">"{t.quote}"</p>
                    <div className="author">
                        <img src={t.avatar} alt={t.name} />
                        <div>
                            <strong>{t.name}</strong>
                            <span>{t.role} at {t.company}</span>
                        </div>
                    </div>
                </div>
            ))}
        </div>
    </div>
</section>
\`;

// === CTA Section ===
const ctaTemplate = \`
<section className="cta">
    <div className="container">
        <div className="cta-content">
            <h2>Ready to get started?</h2>
            <p>Join thousands of developers building the future.</p>
            <div className="cta-buttons">
                <button className="btn btn-primary btn-lg">Start Free Trial</button>
                <button className="btn btn-ghost btn-lg">Talk to Sales</button>
            </div>
        </div>
    </div>
</section>
\`;

export { heroTemplates, featureTemplates, pricingTemplate, testimonialsTemplate, ctaTemplate };
`;
    }
}

export const landingPageBuilder = LandingPageBuilder.getInstance();
