/**
 * 📊 MonitoringStackService
 * 
 * Observability setup:
 * - Prometheus, Grafana, alerting
 */

import { EventEmitter } from 'events';

export class MonitoringStackService extends EventEmitter {
    private static instance: MonitoringStackService;
    private constructor() { super(); }
    static getInstance(): MonitoringStackService {
        if (!MonitoringStackService.instance) {
            MonitoringStackService.instance = new MonitoringStackService();
        }
        return MonitoringStackService.instance;
    }

    generate(): string {
        return `// Monitoring Stack Service - Observability setup
// Generated by Shadow AI

class MonitoringStack {
    // Generate Prometheus config
    async generatePrometheus(targets: string[]): Promise<PrometheusConfig> {
        const response = await llm.chat([{
            role: 'system',
            content: \`Generate Prometheus configuration for these targets.
            Include:
            - Scrape configs
            - Service discovery
            - Recording rules
            - Alert rules\`
        }, {
            role: 'user',
            content: targets.join('\\n')
        }]);
        
        return JSON.parse(response.content);
    }
    
    // Generate Grafana dashboards
    async generateDashboard(metrics: string[], title: string): Promise<GrafanaDashboard> {
        const response = await llm.chat([{
            role: 'system',
            content: \`Generate a Grafana dashboard JSON for these metrics.
            Include:
            - Panels for each metric
            - Variables for filtering
            - Annotations
            - Alerts
            - Proper layout\`
        }, {
            role: 'user',
            content: \`Title: \${title}\nMetrics: \${metrics.join(', ')}\`
        }]);
        
        return JSON.parse(response.content);
    }
    
    // Generate alerting rules
    async generateAlerts(slos: SLODefinition[]): Promise<AlertRules> {
        const response = await llm.chat([{
            role: 'system',
            content: \`Generate Prometheus alerting rules for these SLOs.
            Include:
            - Warning and critical thresholds
            - Multi-window alerts
            - Runbook links
            - Labels for routing\`
        }, {
            role: 'user',
            content: JSON.stringify(slos)
        }]);
        
        return JSON.parse(response.content);
    }
    
    // Generate Datadog config
    async generateDatadog(services: string[]): Promise<string> {
        const response = await llm.chat([{
            role: 'system',
            content: 'Generate Datadog agent configuration and dashboards.'
        }, {
            role: 'user',
            content: services.join(', ')
        }]);
        
        return response.content;
    }
    
    // Generate OpenTelemetry setup
    async generateOTel(language: string): Promise<string> {
        const response = await llm.chat([{
            role: 'system',
            content: \`Generate OpenTelemetry instrumentation code for \${language}.
            Include:
            - Tracer setup
            - Meter setup
            - Auto-instrumentation
            - Exporter configuration\`
        }, {
            role: 'user',
            content: language
        }]);
        
        return response.content;
    }
    
    // Generate SLO definitions
    async defineSLOs(service: string): Promise<SLODefinition[]> {
        const response = await llm.chat([{
            role: 'system',
            content: 'Define SLOs for this service. Return JSON array with objectives, indicators, and targets.'
        }, {
            role: 'user',
            content: service
        }]);
        
        return JSON.parse(response.content);
    }
}

export { MonitoringStack };
`;
    }
}

export const monitoringStackService = MonitoringStackService.getInstance();
