/**
 * 📄 OpenAPI Generator
 * 
 * Generate OpenAPI/Swagger docs:
 * - Specs, UI, validation
 */

import { EventEmitter } from 'events';

export class OpenAPIGenerator extends EventEmitter {
    private static instance: OpenAPIGenerator;

    private constructor() { super(); }

    static getInstance(): OpenAPIGenerator {
        if (!OpenAPIGenerator.instance) {
            OpenAPIGenerator.instance = new OpenAPIGenerator();
        }
        return OpenAPIGenerator.instance;
    }

    generateSpec(): string {
        return `// OpenAPI Specification
// Generated by Shadow AI

const openAPISpec = {
    openapi: '3.0.3',
    info: {
        title: 'My API',
        version: '1.0.0',
        description: 'A comprehensive REST API',
        contact: { email: 'api@example.com' },
        license: { name: 'MIT', url: 'https://opensource.org/licenses/MIT' }
    },
    servers: [
        { url: 'https://api.example.com/v1', description: 'Production' },
        { url: 'https://staging-api.example.com/v1', description: 'Staging' },
        { url: 'http://localhost:3000/v1', description: 'Development' }
    ],
    tags: [
        { name: 'Users', description: 'User management' },
        { name: 'Products', description: 'Product operations' },
        { name: 'Orders', description: 'Order management' }
    ],
    paths: {
        '/users': {
            get: {
                tags: ['Users'],
                summary: 'List all users',
                operationId: 'listUsers',
                parameters: [
                    { name: 'page', in: 'query', schema: { type: 'integer', default: 1 } },
                    { name: 'limit', in: 'query', schema: { type: 'integer', default: 20, maximum: 100 } },
                    { name: 'search', in: 'query', schema: { type: 'string' } }
                ],
                responses: {
                    '200': {
                        description: 'Successful response',
                        content: {
                            'application/json': {
                                schema: {
                                    type: 'object',
                                    properties: {
                                        data: { type: 'array', items: { $ref: '#/components/schemas/User' } },
                                        pagination: { $ref: '#/components/schemas/Pagination' }
                                    }
                                }
                            }
                        }
                    },
                    '401': { $ref: '#/components/responses/Unauthorized' }
                },
                security: [{ bearerAuth: [] }]
            },
            post: {
                tags: ['Users'],
                summary: 'Create a user',
                operationId: 'createUser',
                requestBody: {
                    required: true,
                    content: {
                        'application/json': {
                            schema: { $ref: '#/components/schemas/CreateUser' }
                        }
                    }
                },
                responses: {
                    '201': {
                        description: 'User created',
                        content: { 'application/json': { schema: { $ref: '#/components/schemas/User' } } }
                    },
                    '400': { $ref: '#/components/responses/BadRequest' },
                    '409': { description: 'Email already exists' }
                }
            }
        },
        '/users/{id}': {
            parameters: [
                { name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }
            ],
            get: {
                tags: ['Users'],
                summary: 'Get user by ID',
                operationId: 'getUser',
                responses: {
                    '200': { content: { 'application/json': { schema: { $ref: '#/components/schemas/User' } } } },
                    '404': { $ref: '#/components/responses/NotFound' }
                }
            },
            put: {
                tags: ['Users'],
                summary: 'Update user',
                operationId: 'updateUser',
                requestBody: { content: { 'application/json': { schema: { $ref: '#/components/schemas/UpdateUser' } } } },
                responses: { '200': { content: { 'application/json': { schema: { $ref: '#/components/schemas/User' } } } } }
            },
            delete: {
                tags: ['Users'],
                summary: 'Delete user',
                operationId: 'deleteUser',
                responses: { '204': { description: 'User deleted' } }
            }
        }
    },
    components: {
        schemas: {
            User: {
                type: 'object',
                properties: {
                    id: { type: 'string', format: 'uuid' },
                    email: { type: 'string', format: 'email' },
                    name: { type: 'string' },
                    role: { type: 'string', enum: ['user', 'admin'] },
                    createdAt: { type: 'string', format: 'date-time' }
                },
                required: ['id', 'email', 'name']
            },
            CreateUser: {
                type: 'object',
                properties: {
                    email: { type: 'string', format: 'email' },
                    name: { type: 'string', minLength: 2 },
                    password: { type: 'string', minLength: 8 }
                },
                required: ['email', 'name', 'password']
            },
            UpdateUser: {
                type: 'object',
                properties: {
                    name: { type: 'string' },
                    email: { type: 'string', format: 'email' }
                }
            },
            Pagination: {
                type: 'object',
                properties: {
                    page: { type: 'integer' },
                    limit: { type: 'integer' },
                    total: { type: 'integer' },
                    pages: { type: 'integer' }
                }
            },
            Error: {
                type: 'object',
                properties: {
                    code: { type: 'string' },
                    message: { type: 'string' },
                    details: { type: 'object' }
                }
            }
        },
        responses: {
            BadRequest: { description: 'Bad request', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
            Unauthorized: { description: 'Unauthorized', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
            NotFound: { description: 'Not found', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } }
        },
        securitySchemes: {
            bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
            apiKey: { type: 'apiKey', in: 'header', name: 'X-API-Key' }
        }
    }
};

export default openAPISpec;
`;
    }

    generateSwaggerUI(): string {
        return `// Swagger UI Setup
// Generated by Shadow AI

import swaggerUi from 'swagger-ui-express';
import swaggerJsdoc from 'swagger-jsdoc';

const options = {
    definition: {
        openapi: '3.0.3',
        info: { title: 'My API', version: '1.0.0' }
    },
    apis: ['./src/routes/*.ts'] // Files containing annotations
};

const spec = swaggerJsdoc(options);

// Express setup
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(spec, {
    customCss: '.swagger-ui .topbar { display: none }',
    customSiteTitle: 'API Documentation'
}));

// JSDoc annotations example
/**
 * @openapi
 * /users:
 *   get:
 *     tags: [Users]
 *     summary: List users
 *     responses:
 *       200:
 *         description: Success
 */
router.get('/users', listUsers);
`;
    }
}

export const openAPIGenerator = OpenAPIGenerator.getInstance();
