/**
 * 🎛️ PromptTemplateService
 * 
 * Prompt templates:
 * - Variables, versioning, optimization
 */

import { EventEmitter } from 'events';

export class PromptTemplateService extends EventEmitter {
    private static instance: PromptTemplateService;
    private constructor() { super(); }
    static getInstance(): PromptTemplateService {
        if (!PromptTemplateService.instance) {
            PromptTemplateService.instance = new PromptTemplateService();
        }
        return PromptTemplateService.instance;
    }

    generate(): string {
        return `// Prompt Template Service - Variables, versioning
// Generated by Shadow AI

class PromptTemplateManager {
    private templates: Map<string, PromptTemplate> = new Map();
    
    // Register template
    register(name: string, template: string, variables: string[] = []): void {
        this.templates.set(name, {
            name,
            template,
            variables,
            version: 1,
            createdAt: new Date()
        });
    }
    
    // Render template with variables
    render(name: string, vars: Record<string, any>): string {
        const template = this.templates.get(name);
        if (!template) throw new Error(\`Template not found: \${name}\`);
        
        let result = template.template;
        
        for (const [key, value] of Object.entries(vars)) {
            const regex = new RegExp(\`\\\\{\\\\{\${key}\\\\}\\\\}\`, 'g');
            result = result.replace(regex, String(value));
        }
        
        // Check for unused variables
        const unusedVars = result.match(/\\{\\{\\w+\\}\\}/g);
        if (unusedVars) {
            console.warn(\`Unused variables in template \${name}: \${unusedVars.join(', ')}\`);
        }
        
        return result;
    }
    
    // Create chain of prompts
    createChain(steps: { template: string; vars?: Record<string, any>; outputVar?: string }[]): PromptChain {
        return new PromptChain(this, steps);
    }
    
    // Optimize prompt for token usage
    async optimize(prompt: string, targetTokens: number): Promise<string> {
        const response = await llm.chat([{
            role: 'system',
            content: \`Optimize this prompt to be more concise while preserving meaning. Target: \${targetTokens} tokens.\`
        }, {
            role: 'user',
            content: prompt
        }]);
        
        return response.content;
    }
    
    // Get all templates
    list(): PromptTemplate[] {
        return Array.from(this.templates.values());
    }
    
    // Export templates
    export(): Record<string, string> {
        const result: Record<string, string> = {};
        for (const [name, template] of this.templates) {
            result[name] = template.template;
        }
        return result;
    }
    
    // Import templates
    import(templates: Record<string, string>): void {
        for (const [name, template] of Object.entries(templates)) {
            const vars = this.extractVariables(template);
            this.register(name, template, vars);
        }
    }
    
    private extractVariables(template: string): string[] {
        const matches = template.match(/\\{\\{(\\w+)\\}\\}/g) || [];
        return [...new Set(matches.map(m => m.slice(2, -2)))];
    }
}

class PromptChain {
    constructor(
        private manager: PromptTemplateManager,
        private steps: any[]
    ) {}
    
    async execute(initialVars: Record<string, any> = {}): Promise<Record<string, any>> {
        const context = { ...initialVars };
        
        for (const step of this.steps) {
            const prompt = this.manager.render(step.template, { ...context, ...step.vars });
            
            const response = await llm.chat([{ role: 'user', content: prompt }]);
            
            if (step.outputVar) {
                context[step.outputVar] = response.content;
            }
        }
        
        return context;
    }
}

// Built-in templates
const builtInTemplates = {
    codeReview: \`Review this code for issues:
    
{{code}}

Focus on: {{focus}}
Return JSON with issues found.\`,
    
    generateTest: \`Generate tests for this function:
    
{{code}}

Testing framework: {{framework}}
Include edge cases.\`,
    
    explainCode: \`Explain this code in simple terms:
    
{{code}}

Target audience: {{audience}}\`
};

export { PromptTemplateManager, PromptChain, builtInTemplates };
`;
    }
}

export const promptTemplateService = PromptTemplateService.getInstance();
