/**
 * 📖 Storybook Generator
 * 
 * Generate component documentation:
 * - Storybook with controls, docs
 */

import { EventEmitter } from 'events';

export class StorybookGenerator extends EventEmitter {
    private static instance: StorybookGenerator;

    private constructor() { super(); }

    static getInstance(): StorybookGenerator {
        if (!StorybookGenerator.instance) {
            StorybookGenerator.instance = new StorybookGenerator();
        }
        return StorybookGenerator.instance;
    }

    generate(): string {
        return `// Storybook Configuration
// Generated by Shadow AI

// .storybook/main.ts
import type { StorybookConfig } from '@storybook/nextjs';

const config: StorybookConfig = {
    stories: [
        '../src/**/*.mdx',
        '../src/**/*.stories.@(js|jsx|mjs|ts|tsx)'
    ],
    
    addons: [
        '@storybook/addon-links',
        '@storybook/addon-essentials',
        '@storybook/addon-interactions',
        '@storybook/addon-a11y',
        '@storybook/addon-coverage',
        'storybook-dark-mode'
    ],
    
    framework: {
        name: '@storybook/nextjs',
        options: {}
    },
    
    docs: {
        autodocs: 'tag'
    },
    
    staticDirs: ['../public'],
    
    typescript: {
        check: true,
        reactDocgen: 'react-docgen-typescript'
    }
};

export default config;

// .storybook/preview.tsx
import type { Preview } from '@storybook/react';
import { ThemeProvider } from '../src/components/ThemeProvider';
import '../src/styles/globals.css';

const preview: Preview = {
    parameters: {
        actions: { argTypesRegex: '^on[A-Z].*' },
        controls: {
            matchers: {
                color: /(background|color)$/i,
                date: /Date$/i
            }
        },
        layout: 'centered',
        backgrounds: {
            default: 'light',
            values: [
                { name: 'light', value: '#ffffff' },
                { name: 'dark', value: '#1a1a1a' }
            ]
        }
    },
    
    decorators: [
        (Story) => (
            <ThemeProvider>
                <Story />
            </ThemeProvider>
        )
    ]
};

export default preview;

// === Component Story Example ===
// Button.stories.tsx
import type { Meta, StoryObj } from '@storybook/react';
import { fn } from '@storybook/test';
import { Button } from './Button';

const meta: Meta<typeof Button> = {
    title: 'Components/Button',
    component: Button,
    tags: ['autodocs'],
    
    parameters: {
        layout: 'centered',
        docs: {
            description: {
                component: 'A versatile button component with multiple variants and sizes.'
            }
        }
    },
    
    argTypes: {
        variant: {
            control: 'select',
            options: ['primary', 'secondary', 'outline', 'ghost', 'destructive'],
            description: 'The visual style of the button'
        },
        size: {
            control: 'radio',
            options: ['sm', 'md', 'lg'],
            description: 'The size of the button'
        },
        disabled: {
            control: 'boolean'
        },
        loading: {
            control: 'boolean'
        },
        children: {
            control: 'text'
        }
    },
    
    args: {
        onClick: fn(),
        children: 'Button'
    }
};

export default meta;
type Story = StoryObj<typeof meta>;

// Default story
export const Default: Story = {
    args: {
        variant: 'primary',
        size: 'md'
    }
};

// All variants
export const Variants: Story = {
    render: () => (
        <div style={{ display: 'flex', gap: '1rem' }}>
            <Button variant="primary">Primary</Button>
            <Button variant="secondary">Secondary</Button>
            <Button variant="outline">Outline</Button>
            <Button variant="ghost">Ghost</Button>
            <Button variant="destructive">Destructive</Button>
        </div>
    )
};

// All sizes
export const Sizes: Story = {
    render: () => (
        <div style={{ display: 'flex', gap: '1rem', alignItems: 'center' }}>
            <Button size="sm">Small</Button>
            <Button size="md">Medium</Button>
            <Button size="lg">Large</Button>
        </div>
    )
};

// With icon
export const WithIcon: Story = {
    args: {
        children: (
            <>
                <PlusIcon />
                Add Item
            </>
        )
    }
};

// Loading state
export const Loading: Story = {
    args: {
        loading: true,
        children: 'Loading...'
    }
};

// Disabled
export const Disabled: Story = {
    args: {
        disabled: true
    }
};

// Interactive playground
export const Playground: Story = {
    args: {
        variant: 'primary',
        size: 'md',
        children: 'Click me'
    }
};

// === MDX Documentation ===
// Button.mdx
import { Canvas, Meta, Story, Controls, Source } from '@storybook/blocks';
import * as ButtonStories from './Button.stories';

<Meta of={ButtonStories} />

# Button

A versatile button component for user interactions.

## Usage

\\\`\\\`\\\`tsx
import { Button } from '@/components/Button';

<Button variant="primary" size="md" onClick={() => alert('Clicked!')}>
  Click me
</Button>
\\\`\\\`\\\`

## Variants

<Canvas of={ButtonStories.Variants} />

## Sizes

<Canvas of={ButtonStories.Sizes} />

## Props

<Controls />

## Accessibility

- Uses semantic \\\`<button>\\\` element
- Includes focus states for keyboard navigation
- Loading state includes aria-busy attribute
- Disabled state includes aria-disabled attribute

export { meta };
`;
    }
}

export const storybookGenerator = StorybookGenerator.getInstance();
