/**
 * 🧪 Test Generator
 * 
 * Generate tests:
 * - Unit tests (Jest, Vitest)
 * - E2E tests (Playwright, Cypress)
 */

import { EventEmitter } from 'events';

export type TestFramework = 'jest' | 'vitest' | 'mocha' | 'playwright' | 'cypress';

export class TestGenerator extends EventEmitter {
    private static instance: TestGenerator;

    private constructor() { super(); }

    static getInstance(): TestGenerator {
        if (!TestGenerator.instance) {
            TestGenerator.instance = new TestGenerator();
        }
        return TestGenerator.instance;
    }

    getFrameworks(): TestFramework[] {
        return ['jest', 'vitest', 'mocha', 'playwright', 'cypress'];
    }

    generateUnitTest(framework: TestFramework, componentName: string): string {
        switch (framework) {
            case 'jest':
            case 'vitest':
                return this.generateVitestTest(componentName);
            case 'mocha':
                return this.generateMochaTest(componentName);
            default:
                return this.generateVitestTest(componentName);
        }
    }

    generateE2ETest(framework: TestFramework): string {
        switch (framework) {
            case 'playwright':
                return this.generatePlaywright();
            case 'cypress':
                return this.generateCypress();
            default:
                return this.generatePlaywright();
        }
    }

    private generateVitestTest(name: string): string {
        return `// ${name} Tests
// Generated by Shadow AI

import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { ${name} } from './${name}';

// Mock dependencies
vi.mock('../api/client', () => ({
    fetchData: vi.fn()
}));

describe('${name}', () => {
    const user = userEvent.setup();
    
    beforeEach(() => {
        vi.clearAllMocks();
    });

    afterEach(() => {
        vi.restoreAllMocks();
    });

    it('should render correctly', () => {
        render(<${name} />);
        expect(screen.getByRole('main')).toBeInTheDocument();
    });

    it('should handle user interaction', async () => {
        render(<${name} />);
        
        const button = screen.getByRole('button', { name: /submit/i });
        await user.click(button);
        
        expect(screen.getByText(/success/i)).toBeInTheDocument();
    });

    it('should display loading state', async () => {
        render(<${name} />);
        
        expect(screen.getByRole('progressbar')).toBeInTheDocument();
        
        await waitFor(() => {
            expect(screen.queryByRole('progressbar')).not.toBeInTheDocument();
        });
    });

    it('should handle errors gracefully', async () => {
        const mockError = new Error('Failed to fetch');
        vi.mocked(fetchData).mockRejectedValue(mockError);
        
        render(<${name} />);
        
        await waitFor(() => {
            expect(screen.getByText(/error/i)).toBeInTheDocument();
        });
    });

    it('should match snapshot', () => {
        const { container } = render(<${name} />);
        expect(container).toMatchSnapshot();
    });

    describe('with props', () => {
        it('should render with custom props', () => {
            render(<${name} title="Custom Title" />);
            expect(screen.getByText('Custom Title')).toBeInTheDocument();
        });
    });
});

// Hook tests
describe('use${name}', () => {
    it('should return initial state', () => {
        const { result } = renderHook(() => use${name}());
        expect(result.current.data).toBeNull();
        expect(result.current.loading).toBe(false);
    });

    it('should fetch data on mount', async () => {
        const { result } = renderHook(() => use${name}());
        
        await waitFor(() => {
            expect(result.current.data).toBeDefined();
        });
    });
});
`;
    }

    private generateMochaTest(name: string): string {
        return `// ${name} Tests (Mocha)
// Generated by Shadow AI

import { expect } from 'chai';
import sinon from 'sinon';

describe('${name}', function() {
    let sandbox;
    
    beforeEach(function() {
        sandbox = sinon.createSandbox();
    });
    
    afterEach(function() {
        sandbox.restore();
    });

    it('should initialize correctly', function() {
        const instance = new ${name}();
        expect(instance).to.be.instanceOf(${name});
    });

    it('should process data', async function() {
        const instance = new ${name}();
        const result = await instance.process({ id: 1 });
        expect(result).to.have.property('success', true);
    });

    it('should handle errors', async function() {
        const instance = new ${name}();
        
        try {
            await instance.process(null);
            expect.fail('Should have thrown');
        } catch (error) {
            expect(error.message).to.include('Invalid input');
        }
    });

    context('with mocked dependencies', function() {
        it('should call external service', async function() {
            const stub = sandbox.stub(externalService, 'call').resolves({ data: 'test' });
            
            const instance = new ${name}();
            await instance.fetchExternal();
            
            expect(stub.calledOnce).to.be.true;
        });
    });
});
`;
    }

    private generatePlaywright(): string {
        return `// Playwright E2E Tests
// Generated by Shadow AI

import { test, expect, Page } from '@playwright/test';

test.describe('Application E2E Tests', () => {
    test.beforeEach(async ({ page }) => {
        await page.goto('/');
    });

    test('should load homepage', async ({ page }) => {
        await expect(page).toHaveTitle(/My App/);
        await expect(page.locator('h1')).toContainText('Welcome');
    });

    test('should navigate to login', async ({ page }) => {
        await page.click('text=Login');
        await expect(page).toHaveURL(/.*login/);
    });

    test('should complete login flow', async ({ page }) => {
        await page.goto('/login');
        
        await page.fill('[data-testid="email"]', 'test@example.com');
        await page.fill('[data-testid="password"]', 'password123');
        await page.click('button[type="submit"]');
        
        await expect(page).toHaveURL(/.*dashboard/);
        await expect(page.locator('[data-testid="user-menu"]')).toBeVisible();
    });

    test('should show validation errors', async ({ page }) => {
        await page.goto('/login');
        await page.click('button[type="submit"]');
        
        await expect(page.locator('.error-message')).toContainText('Email is required');
    });

    test('should create new item', async ({ page }) => {
        await login(page);
        await page.goto('/items/new');
        
        await page.fill('[name="title"]', 'Test Item');
        await page.fill('[name="description"]', 'Test Description');
        await page.click('button[type="submit"]');
        
        await expect(page.locator('.toast')).toContainText('Created successfully');
        await expect(page).toHaveURL(/.*items\\/\\d+/);
    });

    test('should handle API errors', async ({ page }) => {
        await page.route('**/api/items', (route) => {
            route.fulfill({ status: 500, body: 'Server Error' });
        });
        
        await page.goto('/items');
        await expect(page.locator('.error-banner')).toBeVisible();
    });

    test('should be responsive', async ({ page }) => {
        await page.setViewportSize({ width: 375, height: 667 });
        await expect(page.locator('.mobile-menu')).toBeVisible();
        
        await page.setViewportSize({ width: 1920, height: 1080 });
        await expect(page.locator('.desktop-nav')).toBeVisible();
    });

    test('accessibility check', async ({ page }) => {
        const accessibilityScanResults = await new AxeBuilder({ page }).analyze();
        expect(accessibilityScanResults.violations).toEqual([]);
    });
});

async function login(page: Page) {
    await page.goto('/login');
    await page.fill('[data-testid="email"]', 'test@example.com');
    await page.fill('[data-testid="password"]', 'password123');
    await page.click('button[type="submit"]');
    await page.waitForURL(/.*dashboard/);
}

// Visual regression
test('visual regression - homepage', async ({ page }) => {
    await page.goto('/');
    await expect(page).toHaveScreenshot('homepage.png');
});

// Performance
test('performance - homepage load', async ({ page }) => {
    await page.goto('/');
    
    const metrics = await page.evaluate(() => JSON.stringify(window.performance.timing));
    const timing = JSON.parse(metrics);
    
    const loadTime = timing.loadEventEnd - timing.navigationStart;
    expect(loadTime).toBeLessThan(3000);
});
`;
    }

    private generateCypress(): string {
        return `// Cypress E2E Tests
// Generated by Shadow AI

describe('Application E2E Tests', () => {
    beforeEach(() => {
        cy.visit('/');
    });

    it('should load homepage', () => {
        cy.title().should('contain', 'My App');
        cy.get('h1').should('contain', 'Welcome');
    });

    it('should complete login flow', () => {
        cy.visit('/login');
        
        cy.get('[data-testid="email"]').type('test@example.com');
        cy.get('[data-testid="password"]').type('password123');
        cy.get('button[type="submit"]').click();
        
        cy.url().should('include', '/dashboard');
        cy.get('[data-testid="user-menu"]').should('be.visible');
    });

    it('should CRUD items', () => {
        cy.login('test@example.com', 'password123');
        
        // Create
        cy.visit('/items/new');
        cy.get('[name="title"]').type('Test Item');
        cy.get('button[type="submit"]').click();
        cy.get('.toast').should('contain', 'Created');
        
        // Read
        cy.get('[data-testid="item-list"]').should('contain', 'Test Item');
        
        // Update
        cy.get('[data-testid="edit-btn"]').first().click();
        cy.get('[name="title"]').clear().type('Updated Item');
        cy.get('button[type="submit"]').click();
        
        // Delete
        cy.get('[data-testid="delete-btn"]').first().click();
        cy.get('.confirm-dialog button').contains('Yes').click();
        cy.get('[data-testid="item-list"]').should('not.contain', 'Updated Item');
    });

    it('should handle network errors', () => {
        cy.intercept('GET', '/api/items', { statusCode: 500 }).as('getItems');
        cy.visit('/items');
        cy.wait('@getItems');
        cy.get('.error-message').should('be.visible');
    });

    it('should be responsive', () => {
        // Mobile
        cy.viewport('iphone-x');
        cy.get('.mobile-menu').should('be.visible');
        
        // Desktop
        cy.viewport('macbook-15');
        cy.get('.desktop-nav').should('be.visible');
    });
});

// Custom commands
Cypress.Commands.add('login', (email, password) => {
    cy.session([email, password], () => {
        cy.visit('/login');
        cy.get('[data-testid="email"]').type(email);
        cy.get('[data-testid="password"]').type(password);
        cy.get('button[type="submit"]').click();
        cy.url().should('include', '/dashboard');
    });
});
`;
    }

    generateAPITest(): string {
        return `// API Tests
// Generated by Shadow AI

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import supertest from 'supertest';
import { app } from '../src/app';

const request = supertest(app);

describe('API Tests', () => {
    let authToken: string;
    let createdId: string;

    beforeAll(async () => {
        // Get auth token
        const res = await request
            .post('/api/auth/login')
            .send({ email: 'test@example.com', password: 'password' });
        authToken = res.body.token;
    });

    describe('GET /api/items', () => {
        it('should return 401 without auth', async () => {
            const res = await request.get('/api/items');
            expect(res.status).toBe(401);
        });

        it('should return items with auth', async () => {
            const res = await request
                .get('/api/items')
                .set('Authorization', \`Bearer \${authToken}\`);
            
            expect(res.status).toBe(200);
            expect(res.body).toBeInstanceOf(Array);
        });

        it('should paginate results', async () => {
            const res = await request
                .get('/api/items?page=1&limit=10')
                .set('Authorization', \`Bearer \${authToken}\`);
            
            expect(res.body.data.length).toBeLessThanOrEqual(10);
            expect(res.body.meta.page).toBe(1);
        });
    });

    describe('POST /api/items', () => {
        it('should create item', async () => {
            const res = await request
                .post('/api/items')
                .set('Authorization', \`Bearer \${authToken}\`)
                .send({ title: 'Test', description: 'Description' });
            
            expect(res.status).toBe(201);
            expect(res.body.title).toBe('Test');
            createdId = res.body.id;
        });

        it('should validate input', async () => {
            const res = await request
                .post('/api/items')
                .set('Authorization', \`Bearer \${authToken}\`)
                .send({});
            
            expect(res.status).toBe(400);
            expect(res.body.errors).toBeDefined();
        });
    });

    describe('PUT /api/items/:id', () => {
        it('should update item', async () => {
            const res = await request
                .put(\`/api/items/\${createdId}\`)
                .set('Authorization', \`Bearer \${authToken}\`)
                .send({ title: 'Updated' });
            
            expect(res.status).toBe(200);
            expect(res.body.title).toBe('Updated');
        });
    });

    describe('DELETE /api/items/:id', () => {
        it('should delete item', async () => {
            const res = await request
                .delete(\`/api/items/\${createdId}\`)
                .set('Authorization', \`Bearer \${authToken}\`);
            
            expect(res.status).toBe(204);
        });
    });
});
`;
    }
}

export const testGenerator = TestGenerator.getInstance();
