/**
 * SSR/SSG Page Generator
 * 
 * Generate server-side rendered and static pages.
 */

import { EventEmitter } from 'events';

interface PageConfig {
    name: string;
    path: string;
    dataSource?: string;
}

export class SSRPageGenerator extends EventEmitter {
    private static instance: SSRPageGenerator;

    private constructor() { super(); }

    static getInstance(): SSRPageGenerator {
        if (!SSRPageGenerator.instance) {
            SSRPageGenerator.instance = new SSRPageGenerator();
        }
        return SSRPageGenerator.instance;
    }

    generateNextJSPage(config: PageConfig): string {
        return `import { GetServerSideProps } from 'next';

interface ${config.name}Props {
  data: any;
}

export default function ${config.name}({ data }: ${config.name}Props) {
  return (
    <div>
      <h1>${config.name}</h1>
      <pre>{JSON.stringify(data, null, 2)}</pre>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  // Fetch data on each request
  ${config.dataSource ? `const res = await fetch('${config.dataSource}');
  const data = await res.json();` : 'const data = {};'}
  
  return { props: { data } };
};`;
    }

    generateStaticPage(config: PageConfig): string {
        return `import { GetStaticProps, GetStaticPaths } from 'next';

interface ${config.name}Props {
  data: any;
}

export default function ${config.name}({ data }: ${config.name}Props) {
  return (
    <div>
      <h1>${config.name}</h1>
      <pre>{JSON.stringify(data, null, 2)}</pre>
    </div>
  );
}

export const getStaticPaths: GetStaticPaths = async () => {
  // Generate paths at build time
  return { paths: [], fallback: 'blocking' };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  ${config.dataSource ? `const res = await fetch('${config.dataSource}');
  const data = await res.json();` : 'const data = {};'}
  
  return {
    props: { data },
    revalidate: 60, // ISR: regenerate every 60 seconds
  };
};`;
    }

    generateDynamicPage(config: PageConfig): string {
        return `'use client';

import { useEffect, useState } from 'react';

export default function ${config.name}() {
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchData() {
      try {
        ${config.dataSource ? `const res = await fetch('${config.dataSource}');
        const json = await res.json();
        setData(json);` : 'setData({});'}
      } catch (error) {
        console.error('Failed to fetch:', error);
      } finally {
        setLoading(false);
      }
    }
    fetchData();
  }, []);

  if (loading) return <div>Loading...</div>;
  
  return (
    <div>
      <h1>${config.name}</h1>
      <pre>{JSON.stringify(data, null, 2)}</pre>
    </div>
  );
}`;
    }

    generateLayout(): string {
        return `import { ReactNode } from 'react';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'My App',
  description: 'Generated by Shadow AI',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav>{/* Navigation */}</nav>
        </header>
        <main>{children}</main>
        <footer>{/* Footer */}</footer>
      </body>
    </html>
  );
}`;
    }

    generateErrorPage(): string {
        return `'use client';

export default function Error({ error, reset }: { error: Error; reset: () => void }) {
  return (
    <div className="error-page">
      <h1>Something went wrong!</h1>
      <p>{error.message}</p>
      <button onClick={reset}>Try again</button>
    </div>
  );
}`;
    }
}

export const ssrPageGenerator = SSRPageGenerator.getInstance();
